### ISSUE TITLE
new device Id and product Ids from EMS+ products

### ISSUE THREAD

**Issue by moustic999** [proddy/EMS-ESP#105]
here are few new types and productId I found from a tester : 

token 0x20 productId 160 MM100 Mixing valve  version NF04.05
token 0x21 productId 160 MM100 Mixing valve  version NF04.05

token 0x08 productId 208 Buderus GB192-25KW version 01.04

all these 3 are EMS+ 

hope this helps

**Comment by proddy** [comment]
Awesome, thanks. I’ll add them to 1.7 as soon as I’m near a laptop
