### ISSUE TITLE
Unknown DeviceID 0x21

### ISSUE THREAD

**Issue by GARLAGANDIS** [proddy/EMS-ESP#111]
![IMG_20190516_220421](https://user-images.githubusercontent.com/11977327/57883495-9a0acc00-7826-11e9-8ad5-316ffb1a327d.jpg)
![IMG_20190516_220518](https://user-images.githubusercontent.com/11977327/57883533-bf97d580-7826-11e9-999b-a3b802dd2f13.jpg)

**Comment by proddy** [comment]
added, thanks for reporting.
