### ISSUE TITLE
ultrasonic sensors on the wemos?

### ISSUE THREAD

**Issue by GARLAGANDIS** [proddy/EMS-ESP#114]
Is it possible to configure a few pins of the Wemos as inputs for sensors? I would like to build a level gauge for my oil tanks with a few ultrasonic sensors.

**Comment by proddy** [comment]
yes, we could extend the project to support external custom code but you'll need to program the external calls yourself e.g. enabling the gpio in setup() and capturing the sending MQTT data in the loop() section. How many pins would you need?

**Comment by susisstrolch** [comment]
Stupid question...
why not use the burner runtime (the nozzle usually have a throughput ~2.1l/hr) to calculate the consumption? I do it since 3 years - and it's much more precise than a ultrasonic sensor...
