### ISSUE TITLE
unknown? (DeviceID:0x10 ProductID:192 Version:53.02) (FW120)

### ISSUE THREAD

**Issue by FrankRenp** [proddy/EMS-ESP#122]
These 2 EMS devices were detected:
 Bosch Condens 2500/Junkers Heatronics3 (DeviceID:0x08 ProductID:95 Version:18.08)
 unknown? (DeviceID:0x10 ProductID:192 Version:53.02)

Unknown device is a Junkers FW120. 

![Junkers_FW120](https://user-images.githubusercontent.com/46407460/58758143-2996c700-8517-11e9-9783-64926850df40.jpg)

**Comment by proddy** [comment]
thanks, added to ems_devices.h and it'll be in the next build
