### ISSUE TITLE
Text formatting issue in help menu of telnet console

### ISSUE THREAD

**Issue by Vuego123** [proddy/EMS-ESP#134]
See screenshot in attachment. When opening the help menu in the telnet console, the text formatting is messed up. 

Version 1.8.1b1

![telnet console](https://user-images.githubusercontent.com/39829323/59792806-4da72600-92d5-11e9-88b2-16eb648064d9.png)

**Comment by proddy** [comment]
oh, that sucks. which telnet app are you using so I can reproduce & debug ?

**Comment by Vuego123** [comment]
Never mind, it suddenly disappeared. So it must have been an issue on my side.

Yesterday, I did several builds and the issue was always there, now it disappeared after a new build & upload. If it pops up again, I'll let you know.
