### ISSUE TITLE
WIFI credential size doesn‘t Match underlying API

### ISSUE THREAD

**Issue by susisstrolch** [proddy/EMS-ESP#140]
When using the webinterface SSID and password are effectivly restricted to 15bytes each. 
The underlying API has 32char for SSID and 64char for password. 
EMS-ESP shouldn‘t restrict those sizes.

**Comment by proddy** [comment]
true. I'll change that. I'm re-writing the complete web interface so will take this into account. I'm fed up with Telnet ;-)

**Comment by susisstrolch** [comment]
I've made a fix for MAX_PWD_LEN and MAX_SSID_LEN - both telnet/serial and webbrowser.
Now I can at least connect again to WIFI (my pwd is 16char ;))
Shall I attach the diff?

**Comment by proddy** [comment]
2 PR is easy, less work for me to do. Thanks for fixing though! 

On a different note you may have noticed I put back the old Tx code and tx_mode options. The Tx logic (tx_mode=2) causes frequent ESP resets. I haven't been able to debug it - perhaps you can take a look?

**Comment by susisstrolch** [comment]
Jep - Susi gave the permission to temporary put a 20m wire from cellar through the whole house to the office 😁

Von meinem iPad gesendet

**Comment by proddy** [comment]
LOL! I did the same, but luckily my office is on the 2nd floor. It'll make debugging much easier.

**Comment by proddy** [comment]
added. thanks
