### ISSUE TITLE
1.8.1 b6 Web interface not working as expected

### ISSUE THREAD

**Issue by Chaot1** [proddy/EMS-ESP#142]
I tried to use the 1.81 b6 Version.
When i start the Webinterface on 192.168.4.1 i can see the both fields for SSID and Pass, but when i try to enter anything the page get refreshed and i must start again.
It's not possible to enter the whole Data.

I use for connection a Android Smartphone

**Comment by susisstrolch** [comment]
Use the diff from #140 - it increases SSID, password and also the refresh (120s).

**Comment by proddy** [comment]
its also a bug in the html. fixed now. Will upload soon and merge in @susisstrolch change too
