### ISSUE TITLE
UBAMonitorSlow not processed since commit "add check for max telegram length"

### ISSUE THREAD

**Issue by Vuego123** [proddy/EMS-ESP#143]
Since commit "add check for max telegram length" (4b28a1d) the UBAMonitorSlow messages are no longer processed. Is the max telegram length check too strict?

An example of how the 0x19 UBAMonitorSlow looks with version 1.8

(00:02:30.536) Boiler -> all, type 0x19 telegram: 88 00 19 00 00 DC 80 00 80 00 FF FF 00 00 00 21 9A 06 E1 7C 00 00 00 06 C2 13 00 1E 90 80 00 (CRC=36) #data=27
<--- UBAMonitorSlow(0x19)

**Comment by proddy** [comment]
well spotted, fixed!
