### ISSUE TITLE
MQTT | Send control commands to the EMS gateway

### ISSUE THREAD

**Issue by mf01** [proddy/EMS-ESP#148]
I'm using the new EMS gateway from bbqkees and it works good.

Unfortunately I don't have found how I can control the boiler through MQTT.

I've tried this MQTT messages without success....

```
$ mosquitto_pub -h *** -t home/ems-esp/boiler_data/wWSelTemp -m 59
$ mosquitto_pub -h *** -t home/ems-esp/boiler_data -m '{"wWSelTemp":59}'
$ mosquitto_pub -h *** -t home/ems-esp/boiler_data/set -m '{"wWSelTemp":59}'
$ mosquitto_pub -h *** -t home/ems-esp/boiler_data/wWSelTemp/set -m 59
$ mosquitto_pub -h *** -t home/ems-esp/boiler_data/wWSelTemp/cmd -m 59
$ mosquitto_pub -h *** -t home/ems-esp/boiler_data/cmd -m '{"wWSelTemp":59}'
```

Instead of wwSelTemp wwHeat and other options should be also possible.

Can somebody help me?

**Comment by proddy** [comment]
I'm not at home so can't test but to send MQTT use the topic for example `home/ems-esp/thermostat_cmd_temp` with a payload holding the value.  

Not all functionality is supported but it's easy to extend in the code (ems-esp.cpp).

See https://github.com/proddy/EMS-ESP/wiki/MQTT
