### ISSUE TITLE
Home Assistant integration

### ISSUE THREAD

**Issue by Sonusss** [proddy/EMS-ESP#149]
When trying to integrate into HA I got lot of error message when checking config like:
Invalid config for [climate.mqtt]: [state_topic] is an invalid option for [climate.mqtt]. Check: climate.mqtt->state_topic. (See ?, line ?). Please check the docs at https://home-assistant.io/components/climate.mqtt/
Invalid config for [climate.mqtt]: [state_topic] is an invalid option for [climate.mqtt]. Check: climate.mqtt->state_topic. (See ?, line ?). Please check the docs at https://home-assistant.io/components/climate.mqtt/
Invalid config for [climate.mqtt]: [state_topic] is an invalid option for [climate.mqtt]. Check: climate.mqtt->state_topic. (See ?, line ?). Please check the docs at https://home-assistant.io/components/climate.mqtt/
Invalid config for [climate.mqtt]: [state_topic] is an invalid option for [climate.mqtt]. Check: climate.mqtt->state_topic. (See ?, line ?). Please check the docs at https://home-assistant.io/components/climate.mqtt/
Platform not found: climate.template

**Comment by proddy** [comment]
couple of things to try
- check what the MQTT messages are coming into the broker
- check what HA is doing with the MQTT messages (by adding HA logging for MQTT debug)
- what does your climate.yaml look like?
- which model thermostat are you using? Does it have auto, manual and off modes?

**Comment by Sonusss** [comment]
I finally figured out how to do it
