### ISSUE TITLE
Some temp values are multiplicated by 10 in HA

### ISSUE THREAD

**Issue by Sonusss** [proddy/EMS-ESP#158]
I finally get it working with HA.
However some temp value are multiplied by 10 for example, current room temparature: 230°C

**Comment by proddy** [comment]
Are you using 1.8.1 beta?

Do the values show correctly when in telnet after an `info` command?

**Comment by Sonusss** [comment]
Yes it does...
However decimal separator is dot not coma

**Comment by proddy** [comment]
ok, I think this is fixed in 1.8.1b22

The decimal separator is "."
