### ISSUE TITLE
Led remains on after reboot

### ISSUE THREAD

**Issue by mrfixit1** [proddy/EMS-ESP#167]
Issue: after every reboot, both soft and hard, the blue led on the wemos board remains on, even though both the info and set commands say that it is off.

Workaround: manual set led off command. 

Setup: v1.8.1 on wemos d1 mini, bbqkees interface board, Nefit Topline Compact boiler, RC20 thermostat.

**Comment by proddy** [comment]
Thanks. I’ll look into that. Is the value of led_gpio set to 2 ? (which is LED_BULLETIN  when Pio uses the board d1_mini)

**Comment by mrfixit1** [comment]
Yes. Btw stating the obvious: the issue has zero functional impact, so fixing it isn't urgent.

**Comment by proddy** [comment]
fixed, in 1.8.2 and the upcoming 1.9. Thanks!

**Comment by mrfixit1** [comment]
Thanks Paul: updated to 1.8.2 and fix verified, very quick work!
