### ISSUE TITLE
Gather EMS Ids & Versions

### ISSUE THREAD

**Issue by sysrun** [proddy/EMS-ESP#18]
I am trying to implement my RC35 (Buderus) controller i found out that the current implementation is not able to gather the thermostat information correctly as my RC35 is using HK1 for heating. 
So currently for the code is not able to distinguish between RC30 & RC35 as both use the id 0x10

I'd like to gather some more informations about the different setups.

I issued the following commands to get some more infos:

BC10:
r 0b 88 02 00 08 -> Product ID 123. Version 04.05

Original RC35:
r 0b 90 02 00 08 -> Product ID 86. Version 01.15

Maybe we can compile a list of Product IDs & Versions somehow

**Comment by proddy** [comment]
Awesome! I was waiting for this. How are your programming skills? I can do
the first version and push it my dev branch.

**Comment by sysrun** [comment]
Well, skills are quite good - i can understand 90% of the C code ;) Binary ops etc are no problem. So extending of existing code is not really a problem (adding new ems telegrams etc.)

**Comment by SpaceTeddy** [comment]
dear sysrun,
my Sieger BK15 with es73 (RC30 like) controller:
`
Sending raw telegram: 0B 88 02 00 08 (CRC=94, #data=1)
(01:19:52) Corrupt telegram: telegram: 00 08 (CRC=94)
(01:19:52) Boiler -> me, type 0x02 telegram: 08 0B 02 00 40 03 06 00 00 00 00 00 (CRC=DE, #data=8)
(01:19:52) <--- Version(0x02) received
(01:19:52) Product ID 64. Version 03.06
`

`
(01:20:27) Sending raw telegram: 0B 90 02 00 08 (CRC=54, #data=1)
(01:20:27) Corrupt telegram: telegram: 00 08 (CRC=54)
(01:20:27) Thermostat -> me, type 0x02 telegram: 10 0B 02 00 4C 02 08 (CRC=18, #data=3)
(01:20:27) <--- Version(0x02) received
(01:20:27) Product ID 76. Version 02.08
`

**Comment by proddy** [comment]
I'm working on some new code that auto detects the EMS devices. I've
included the Sieger BK15 and ES73 but will need your help to fine tune the
code. I'm testing now and hope to push to GitHub this weekend.

**Comment by SpaceTeddy** [comment]
yes for sure, I can test it.

**Comment by sysrun** [comment]
Just tried the 1.2.2 - works for me :) Awesome!
Found a Boiler compatible device, model MC10/UBA3 Boiler with TypeID 0x08, Product ID 123, Version 04.05
Found a Thermostat. Model RC35 with TypeID 0x10, Product ID 86, Version 01.15

One thing: I don't have any room sensor/thermostat (RC35 is build into the heater).
**_Current room temperature: 3200.0 C_**

**Comment by proddy** [comment]
can you do a 't 3e' which will fetch the status message telegram from built-in thermostat, and post the results back. The room temperature should be byte 3 and 4 of the data package. If there is no sensor it should be 0x80 and 0x00.

**Comment by sysrun** [comment]
Requesting type RC35StatusMessage(0x3E) from dest 0x10
(09:52:35) Sending read of type 0x3E to 0x10: telegram: 0B 90 3E 00 63 (CRC=CF), #data=1
(09:52:35) Thermostat -> me, type 0x3E telegram: 10 0B 3E 00 80 02 28 7D 00 00 00 00 00 00 00 00 64 11 3A 00 (CRC=4E), #data=16

**Comment by proddy** [comment]
Ok, think I fixed this in my latest 1.2.3

**Comment by sysrun** [comment]
Looks good now (Current room temperature: ? C)

**Comment by SpaceTeddy** [comment]
- two additional Product ID'd and SW Versions, because I've installed an RFM20 + RC20RF as well.

`- RFM20 -> ID = 0x09 -> raw telegram: 08 89 02 00 63 (CRC=C7), #data=1 -> Unrecognized device found. Product ID 68, Version 02.03`

`- RC20RF -> ID = 0x18 -> raw telegram: 0B 98 02 00 63 (CRC=7F), #data=1 -> Unrecognized device found. Product ID 93, Version 02.00`

**Comment by proddy** [comment]
thanks @SpaceTeddy. These will be included in the next build.

**Comment by Bonusbartus** [comment]
The autodetect is not working for me either, since the last update (comming from 1.2.0) I cannot get any boiler information. I am using a Nefit Topline Compact HRC30 CW5 with a moduline 300 thermostat. 
In the old versions, all data seemed to work perfectly.
the discovered deviceIDs are:
0x08: Unrecognized device found. Product ID 115, Version 03.06
0x09: Unrecognized device found. Product ID 114, Version 01.03

**Comment by proddy** [comment]
That's because these devices haven't been added to the list. You'll need to manually add to ems_devices.h 

For now to get it working, hard code these in my_devices.h like

#define MY_BOILER_MODELID EMS_MODEL_UBA
#define MY_THERMOSTAT_MODELID EMS_MODEL_RC20

**Comment by proddy** [comment]
@Bonusbartus I've added these to version 1.3.2

**Comment by lobocobra** [comment]
Luckily I have no boiler attached, because the water would be quite cold :-)
=> Warm Water current temperature: -3200.0 C

Not a real isse for me, but maybe it makes sense to eliminate values <0° and higher as 110°?

**Comment by proddy** [comment]
Good idea. But can you create a new github bug for this request and I’ll make the change. Thanks

**Comment by proddy** [comment]
@lobocobra for the minus -3200C warm water temperature problem could do a `log v` `boiler read 34` and post back the telegram. The code should be able to detect n/a values.

**Comment by lobocobra** [comment]
Thanks!  with your latest fix the 3200C warm water temperature problem is solved.
