### ISSUE TITLE
no thermostat data with Sieger ES73 since 1.9.1bx

### ISSUE THREAD

**Issue by SpaceTeddy** [proddy/EMS-ESP#185]
Dear Paul,
After an update from master 1.9.0 to 1.9.1b4 or b5, the thermostat data for my Sieger ES73 is not read correctly. Via telnet, no temperature data is shown, via Web interface the Setpoint temperature is round about 4343°C, current temperature could be correct.
I expect, there is something with your heatcircuit change, and I would like to ask you which data/loggings you need to find the root cause. Hope I can help to fix this.

thx

**Comment by proddy** [comment]
oops. I'll look into it. Does the ES73 support multiple heating circuits?

**Comment by SpaceTeddy** [comment]
yes, the ES73 does support up to 4 circuits, i guess .)
The ES73 is more and less a mix of Buderus RC30 and RC35.

**Comment by SpaceTeddy** [comment]
with the latest 1.9.1_b4 I can see the following:
![image](https://user-images.githubusercontent.com/9148964/65271688-eee48900-db1d-11e9-87ee-39e2ccc10161.png)

![image](https://user-images.githubusercontent.com/9148964/65271772-1c313700-db1e-11e9-81ae-228f18338e21.png)

![image](https://user-images.githubusercontent.com/9148964/65271959-76ca9300-db1e-11e9-8a59-bc5ba9d7a68d.png)

any idea?

many thanks

**Comment by SpaceTeddy** [comment]
I recompiled the b4 with:

``
// check if current temp sensor is unavailable
    if (EMS_RxTelegram->data[EMS_OFFSET_RC35StatusMessage_curr] != 0x7D) {
        EMS_Thermostat.hc[hc_num].curr_roomTemp = _toShort(EMS_OFFSET_RC35StatusMessage_curr); // is * 10
    }
``

and it works for me.

**Comment by proddy** [comment]
wow, you fixed a bug!

**Comment by proddy** [comment]
Can we close this now?

**Comment by SpaceTeddy** [comment]
well, for the HC1 current room temperature basically yes, but the ESP detects two HC's and I have only HC1 in use.

**Comment by proddy** [comment]
that shouldn't happen with the latest dev build anymore?

**Comment by SpaceTeddy** [comment]
alright! :)

**Comment by SpaceTeddy** [comment]
Dear Proddy,

since 1.9.1b8, the setpoint temp and the current temp is not shown in telnet and mqtt anymore. I've seen that you modified a lot between b7 and b8. Anything I can test with my ES73 to keep it running again?

thx,
chris

**Comment by proddy** [comment]
is Tx working?

**Comment by proddy** [comment]
oops, found the error!

**Comment by SpaceTeddy** [comment]
yes, fixed!
