### ISSUE TITLE
Some Worcester Bosch boilers do not report water pressure

### ISSUE THREAD

**Issue by zxdavb** [proddy/EMS-ESP#212]
**Bug description**
My combi boiler does not report water pressure via ems-esp. Notably, _all other_ values appear valid (that is, the remainder of telegram 0x18 is as expected).

My boiler is a Worcester Greenstar 30Si NG, but other Worcester Bosch boilers appear to be affected.

Although this boiler has an analog display for pressure and a digital pressure is _not_ available via the built-in controls, there is good evidence that the system has a digital pressure internally that is available to the bus.

**Steps to reproduce**
Via **telnet**, enter the `info` command:
```
EMS-ESP system stats:
  System logging set to None
  LED is on, Listen mode is off
  Boiler is enabled, Thermostat is disabled, Solar Module is disabled, Mixing Module is disabled, Shower Timer is disabled, Shower Alert is disabled

EMS Bus stats:
  Bus is connected, protocol: Junkers HT3
  Rx: # successful read requests=3373, # CRC errors=0
  Tx: Last poll=2.599 seconds ago, # successful write requests=0

Boiler stats:
  Boiler: Buderus GBx72/Nefit Trendline/Junkers Cerapur (ProductID:123 Version:06.00)
    ...
  System pressure: ? bar
    ...
 ```

**Expected behavior**
```
  System pressure: 1.8 bar
```

**Screenshots**
With `log v`, we have:
```
(11:44:30.984) Boiler -> all, type 0x18, telegram: 88 00 18 00 05 01 EF 00 00 00 01 40 50 01 3E 80 00 01 C1 00 00 FF 00 00 00 CB 00 00 00 (CRC=82) #data=25
<--- UBAMonitorFast(0x18)
```

Note that the 22nd data byte is 0xFF (missing).

**Device information**
Via **telnet**, enter the `system` command:
```
ESP8266 System stats:

 [APP] EMS-ESP version: 1.9.2b9
 [APP] MyESP version: 1.2.10
 [APP] Build timestamp: 2019-10-14 18:26:45
 [APP] Uptime: 0 days 11 hours 46 minutes 7 seconds
 [APP] System Load: 6%
 [WIFI] WiFi Hostname: ems-esp
 [WIFI] WiFi IP: 172.27.0.216
 [WIFI] WiFi signal strength: 28%
 [WIFI] WiFi MAC: CC:50:E3:C4:8D:28
 [MQTT] is connected (heartbeat enabled)
 [SYSTEM] System is Stable
 [SYSTEM] Board: PLATFORMIO_D1_MINI
 [SYSTEM] CPU frequency: 80 MHz
 [SYSTEM] SDK version: 2.2.1(cfd48f3)
 [SYSTEM] CPU chip ID: 0xC48D28
 [SYSTEM] Core version: 2_5_2
 [SYSTEM] Boot version: 31
 [SYSTEM] Boot mode: 1
 [SYSTEM] Last reset reason: Restart from terminal
 [SYSTEM] Restart count: 0
 [SYSTEM] rtcmem status: blocks:2 addr:0x60001280
 [SYSTEM] rtcmem 00: 1163087990
 [SYSTEM] rtcmem 01: 65536
 [FLASH] Flash chip ID: 0x1640EF
 [FLASH] Flash speed: 40000000 Hz
 [FLASH] Flash mode: DIO
 [FLASH] Flash size (CHIP): 4194304
 [FLASH] Flash size (SDK): 4194304
 [FLASH] Flash Reserved: 4096
 [MEM] Firmware size: 690256
 [MEM] Max OTA size: 2449408
 [MEM] OTA Reserved: 16384
 [MEM] Free Heap: 25736 bytes initially | 10536 bytes used (40%) | 15200 bytes free (59%)
```

Note that my boiler requires (at least) version 1.9.2 of the firmware.

**Comment by zxdavb** [comment]
If pressure is still available to the bus, then why has it been removed from telegram 0x18?

Assuming that pressure is available to a precision of 0.01 (as it is on another boiler I own, an Intergas Eco RF 36), then that data would no longer fit into a single byte - so it would have to have been move to another (new?) telegram.

Supposing the new telegram is only available polled, rather than periodically broadcast to the bus...

... then the system would be behaving as seen.

** Next steps

The step step would be to identify this new telegram, and poll it.?

**Comment by proddy** [comment]
The system pressure in the UBA Monitor Fast (0x18) telegram shows a value 0xFF meaning "not available" on some Worcester model boilers.

It is available on a Bosch Condens GC9000iWM for example but not all the Worcester Greenstars.

Likewise Boiler Temperature and Boiler Return Temperature are not always available on both these models. I expect the data is somewhere in a separate telegram but without details it will be hard to find as none of this EMS protocol is publically available.

What you could try is capture all the logs from the Boiler with one Pressure setting, then up the Pressure setting and capture a new set. Then painstakingly going through all the telegrams looking for possible changes.

**Comment by zxdavb** [comment]
> What you could try is capture all the logs from the Boiler with one Pressure setting, then up the Pressure setting and capture a new set. Then painstakingly going through all the telegrams looking for possible changes.

As a trial, I have done this via a `log v` for 1 hour.  I found telegrams 07, 14, 16, 18, 19, 1C, 2A, 33, 34.

I did not find anything, but will do 24 hours & have another go.

**Comment by moustic999** [comment]
One question, Can you see the pressure value in a menu on the thermostat ? 
if yes, Can you tell me in which menu / sub menu... that can help to identify the right telegram.
if no, I fear that this value is not reported to the bus !

**Comment by zxdavb** [comment]
I have a **Worcester Bosch Greenstart 27i System Compact**.

From the `device` command:
```
These device IDs are on the EMS Bus: 0x08 0x09
and 2 were recognized by EMS-ESP as:
 Buderus GBx72/Nefit Trendline/Junkers Cerapur (DeviceID:0x08 ProductID:123 Version:06.02)
 Junkers Controller (DeviceID:0x09 ProductID:152 Version:03.01)
```
... and from the `info` command:
```
EMS-ESP system stats:
  System logging set to None
  LED is on, Listen mode is off
  Boiler is enabled, Thermostat is disabled, Solar Module is disabled, Mixing Module is disabled, Shower Timer is disabled, Shower Alert is disabled

EMS Bus stats:
  Bus is connected, protocol: Junkers HT3
  Rx: # successful read requests=28, # CRC errors=0
  Tx: Last poll=2.699 seconds ago, # successful write requests=0

Boiler stats:
  Boiler: Buderus GBx72/Nefit Trendline/Junkers Cerapur (ProductID:123 Version:06.02)
  Central heating: active
  Warm Water activated: on
  Warm Water circulation pump available: off
  Warm Water comfort setting: Eco
  Warm Water selected temperature: 60 C
  Warm Water desired temperature: 70 C
  Warm Water current temperature: ? C
  Warm Water current tap water flow: ? l/min
  Warm Water # starts: ? times
  Warm Water 3-way valve: off
  Selected flow temperature: 60 C
  Current flow temperature: 52.1 C
  Return temperature: 46.1 C
  Gas: on
  Boiler pump: on
  Fan: on
  Ignition: off
  Circulation pump: off
  Burner selected max power: 100 %
  Burner current power: 31 %
  Flame current: 27.7 uA
  System pressure: ? bar
  System service code:  (200)
  Heating temperature setting on the boiler: 60 C
  Boiler circuit pump modulation max power: 100 %
  Boiler circuit pump modulation min power: 60 %
  Boiler temperature: 57.0 C
  Pump modulation: 72 %
  Burner # starts: 9696 times
  Total burner operating time: 62 days 22 hours 51 minutes
  Total heat operating time: 62 days 22 hours 51 minutes
  Total UBA working time: 321 days 13 hours 37 minutes
```

**Comment by zxdavb** [comment]
> One question, Can you see the pressure value in a menu on the thermostat ?
> if yes, Can you tell me in which menu / sub menu... that can help to identify the right telegram.
> if no, I fear that this value is not reported to the bus !

My two WB boiler appear/behave identically.  They have an analog pressure dial, and no pressure is available via the digital display.  However, from their manuals, there is a clear indication of water-pressure error codes, so I still suspect it's a matter of working out what telegram to request.

**Comment by glitter-ball** [comment]
I think a lot of WB boilers have no water pressure sensor at all. I have a Greenstar 24i System ErP and added a Sense II to it. The Sense II constantly complained that the water pressure sensor was faulty. Bosch came and changed the HCM (heat control module) in the boiler for a later software version and the problem went away. Looking inside, there's no sensor fitted, so the boiler relies on an analogue pressure gauge and that's it.

**Comment by PhillyGilly** [comment]
Hello @proddy . As you know I have exactly the same Boiler/Sense II combination as @glitter-ball. When I saw the above I also checked and the only pressure sensor is connected to the front panel gauge by a length of black capillary tube. I would suggest that this issue can be closed next time you are doing house keeping.

**Comment by proddy** [comment]
great! thanks, forgot about this one.
