### ISSUE TITLE
Unknown Device, version 1.9.2

### ISSUE THREAD

**Issue by MiV739** [proddy/EMS-ESP#215]
My Boiler buderus logamax u52-28
      Termostat Logamatic TC100

Via telnet, enter the 'devices' command:

These device IDs are on the EMS Bus: 0x08 0x09 0x18
and 3 were recognized by EMS-ESP as:
 Bosch Condens 2500/Buderus Logamax GB062/Junkers  (DeviceID:0x08 ProductID:95 V                  ersion:13.08)
 unknown? (DeviceID:0x09 ProductID:95 Version:13.08)
 Logamatic TC100/Nefit Moduline Easy (DeviceID:0x18 ProductID:202 Version:02.19)

EMS-ESP version 1.9.2 of the firmware.

**Comment by proddy** [comment]
It must be a built in controller since its Device ID 0x09. Most Logamax's have them. I'm not sure which one and looking through the manuals I couldn't quickly find it. You can safely ignore it.
