### ISSUE TITLE
Dashboard - add values AND re-arrange values

### ISSUE THREAD

**Issue by S-Przybylski** [proddy/EMS-ESP#216]
Dear @proddy 
thanks to you and all contributors for the very good implementation. After weeks of running an old version today i have compiled the 1.9.3b1. No errors no problems. I am impressed!

I noticed that even i have EMS+ devices (GB172-20/SM100/BC25/RC300) installed the EMS mode works without any issue or error!

Here my feature request:
My GB172-20 uses the outdoor temperature to adjust the current flow temp. I do not have a return temperature or boiler temperature. I think the boiler temperature equals more or less the current flow temp.
Could you please also display the outdoor temp on the dashboard?
In addition to that i also prefer to see the water temperatures (at least current)

Perhaps you can arrange the values in different sections, like generic, boiler, heating, warm water, ...

**Comment by proddy** [comment]
Thanks @S-Przybylski for the compliments.

I can extend the web dashboard if the data is available. I think one change is suppressing any temperature or boiler temperatures if they're not available (as this is pointless).

As for the outdoor temp, is it shown in `info`? If so I will add that too.

And for the water temperatures can you describe which values (from again `info`) you're interested in seeing?

And lastly, please help me with a web design for the sections (generic, boiler, heating etc). Its HTML so everything is possible.
