### ISSUE TITLE
make EMS-ESP independant of Home automation softwares

### ISSUE THREAD

**Issue by moustic999** [proddy/EMS-ESP#232]
the different modes returned by thermostat over mqtt have been designed to work with HA only.
for example the RC300 has 2 modes : auto and manual, but manual is reported as "heat" over mqtt. 
this is because Home-Assistant does not know "manual".

same for RC35 where modes day and night are replaced by "heat" and "off".

it is important ems-esp remains independant of home-assistant softwares and keep original name from heater.

for HA user, they can use climate.yaml in doc/home-assistant where the mapping they need can be set up.

The same apply also for mqtt tree name that must remains agnostic. climate.yaml and sensor.yaml can be set up to suit need of HA users.

**Comment by proddy** [comment]
done
