### ISSUE TITLE
Unkown Device - Buderus Logamax Plus GB122-24 KD H

### ISSUE THREAD

**Issue by theloukou** [proddy/EMS-ESP#235]
The boiler cannot be recognized from the ESP.
Log from telnet is below:

These device IDs are on the EMS Bus: 0x08
and 1 were recognized by EMS-ESP as:
unknown? (DeviceID:0x08 ProductID:234 Version:05.03)

**Comment by proddy** [comment]
I'll add to the latest dev branch
