### ISSUE TITLE
old bug re-introduced?

### ISSUE THREAD

**Issue by LineF** [proddy/EMS-ESP#258]
Hi,

since rev. f96e2efe I can't again save values from the Web-UI...
Seems that correction from rev. b8a55a1 has been lost?
Cherry-picking commit b8a55a1 and merging it to latest rev. 1.9.4b24 solves the problem.

Kind regards,
Martin

**Comment by proddy** [comment]
I'll take a look. Does it happen with all the settings pages in the web?

**Comment by LineF** [comment]
Hmm, only quick tested with pull down menu of time zones and enabling/disabling serial port.
I noticed the error when I wanted to initial setup the wifi settings - these didn't work too.

**Comment by proddy** [comment]
ok, should be easy for me to reproduce then.

**Comment by proddy** [comment]
looked like the changes were somehow reversed, I re-committed them.
