### ISSUE TITLE
Topic boiler_data is not submitted after upgrading to 1.9.4

### ISSUE THREAD

**Issue by kkberg** [proddy/EMS-ESP#272]
*Before creating a new issue please check that you have:*

* *searched the existing [issues](https://github.com/proddy/EMS-ESP/issues) (both open and closed)*
* *searched the [wiki help pages](https://github.com/proddy/EMS-ESP/wiki/Troubleshooting)*

*Completing this template will help developers and contributors to address the issue. Try to be as specific and extensive as possible. If the information provided is not enough the issue will likely be closed.*

*You can now remove this line and the above ones. Text in italic is meant to be replaced by your own words. If any of the sections below are not relevant to the issue (for instance, the screenshots) then you can delete them.*

**Topic boiler_data is not submitted after upgrading to 1.9.4**
*in 1.9.3 topic boiler_data is directly submitted to MQTT IOBroker*

**update firmware from 1.9.3 to 1.9.4**
*start module*

**topic boiler_data should be submitted soon**
*I wamt to see boiler_data topic after starting WEMOS D1 Mini*

**Screenshots**
![d101](https://user-images.githubusercontent.com/1121884/71545777-48671a00-298f-11ea-902a-0bfebcb6f6fe.JPG)
![d102](https://user-images.githubusercontent.com/1121884/71545801-8c5a1f00-298f-11ea-9e80-1f01f0f558de.JPG)

**Device information**
MQTT publish log:
  Timestamp:16:35:27 Topic:status Payload:online
  Timestamp:16:35:27 Topic:start Payload:start
  Timestamp:16:40:32 Topic:shower_data Payload:{"timer":"1","alert":"1"}
  Timestamp:16:45:23 Topic:heartbeat Payload:{"version":"1.9.4","IP":"192.168.1.25","rssid":100,"load":1,"uptime":607,"freemem":52,"MQTTdisconnects":0}

MQTT subscriptions:
  Topic:Buderus/Buderus/restart
  Topic:Buderus/Buderus/start
  Topic:Buderus/Buderus/thermostat_cmd_temp1
  Topic:Buderus/Buderus/thermostat_cmd_mode1
  Topic:Buderus/Buderus/thermostat_cmd_temp2
  Topic:Buderus/Buderus/thermostat_cmd_mode2
  Topic:Buderus/Buderus/thermostat_cmd_temp3
  Topic:Buderus/Buderus/thermostat_cmd_mode3
  Topic:Buderus/Buderus/thermostat_cmd_temp4
  Topic:Buderus/Buderus/thermostat_cmd_mode4
  Topic:Buderus/Buderus/thermostat_cmd
  Topic:Buderus/Buderus/boiler_cmd
  Topic:Buderus/Buderus/boiler_cmd_wwactivated
  Topic:Buderus/Buderus/boiler_cmd_wwonetime
  Topic:Buderus/Buderus/boiler_cmd_wwtemp
  Topic:Buderus/Buderus/generic_cmd
  Topic:Buderus/Buderus/shower_data

1.9.3
MQTT publish log:
  Topic:status Payload:online
  Topic:start Payload:start
  Topic:heartbeat Payload:{"version":"1.9.3","IP":"192.168.1.25","rssid":100,"load":3,"uptime":131,"freemem":54,"MQTTdisconnects":0}
  Topic:shower_data Payload:{"timer":"1","alert":"1"}
  Topic:boiler_data Payload:{"selFlowTemp":44,"selBurnPow":72,"curBurnPow":25,"pumpMod":100,"outdoorTemp":1.5,"wWCurTmp":46.1,"wWCurFlow":0,"curFlowTemp":44.1,"burnGas":"on","flameCurr":14.1,"heatPmp":"on","fanWork":"on","ignWork":"off","wWCirc":"off","wWHeat":"off","wWStarts":1209,"wWWorkM":21993,"burnStarts":2729,"burnWorkMin":70419,"heatWorkMin":48426,"ServiceCode":"-H","ServiceCodeNumber":200}
  Topic:tapwater_active Payload:0
  Topic:heating_active Payload:1

MQTT subscriptions:
  Topic:Buderus/Buderus/restart
  Topic:Buderus/Buderus/start
  Topic:Buderus/Buderus/temp1
  Topic:Buderus/Buderus/mode1
  Topic:Buderus/Buderus/temp2
  Topic:Buderus/Buderus/mode2
  Topic:Buderus/Buderus/temp3
  Topic:Buderus/Buderus/mode3
  Topic:Buderus/Buderus/temp4
  Topic:Buderus/Buderus/mode4
  Topic:Buderus/Buderus/thermostat_cmd
  Topic:Buderus/Buderus/boiler_cmd
  Topic:Buderus/Buderus/boiler_cmd_wwactivated
  Topic:Buderus/Buderus/boiler_cmd_wwtemp
  Topic:Buderus/Buderus/generic_cmd
  Topic:Buderus/Buderus/shower_data

**Additional context**
*Add any other context about the problem here.*

**Comment by proddy** [comment]
1.9.5 has some improvements but it’s still not ideal. Can you try that and use publish_time of 10

**Comment by kkberg** [comment]
Need to find the bin for 1.9.5 :)

**Comment by kkberg** [comment]
Changed to dev 1.9.5, but no change. Even with 10 seconds publish time. I go back to 1.9.3. If it helps, I'm going to test coming betas to solve problem.

**Comment by proddy** [comment]
I can't reproduce using the latest 1.9.5. `mqttlog` shows that the boiler_data is sent and in MQTT Explorer I see the inbound messages.

**Comment by kkberg** [comment]
Okay, I give up.

**Comment by kkberg** [comment]
Only for information. Time between topics is too long. Don't know what it is. 1.9.4 never sent boiler_data to iobroker.

![d104](https://user-images.githubusercontent.com/1121884/71777346-e5810e80-2f9e-11ea-8ac5-7728dbbf878e.JPG)

**Comment by proddy** [comment]
Ok, so you are getting the boiler data sent to the MQTT broker. But it just takes a long time? In 1.9.4 what happens when you use these commands in telnet with logging enabled:

`refresh` - does it fetch that data and do a publish?
`publish` - does it publish the data?

also check your `publish_time` parameter.

**Comment by kkberg** [comment]
only heartbeat and shower_data is published
![d106](https://user-images.githubusercontent.com/1121884/71777887-cdad8880-2fa6-11ea-8428-2bf23707feec.JPG)

![d105](https://user-images.githubusercontent.com/1121884/71777875-8aebb080-2fa6-11ea-8118-661b30efa427.JPG)

**Comment by proddy** [comment]
go to telnet
type `log v` BEFORE doing the refresh or publish so you see what is happening
and type `set` to see your settings, check publish_time

https://github.com/proddy/EMS-ESP/wiki/Troubleshooting

**Comment by kkberg** [comment]
![d108](https://user-images.githubusercontent.com/1121884/71780147-47ea0700-2fbf-11ea-8c9b-8728f4d5394e.JPG)
![d110](https://user-images.githubusercontent.com/1121884/71780148-47ea0700-2fbf-11ea-8d73-ea3d5cd2917e.JPG)
![d109](https://user-images.githubusercontent.com/1121884/71780149-48829d80-2fbf-11ea-811e-51c10f86d4d1.JPG)

**Comment by proddy** [comment]
you have listen_mode set to on. Which means no Tx so probably the boiler is not detected. Do you see it in `info`.

**Comment by kkberg** [comment]
I don't want to us Tx and wire is for Tx is also not connected. It works with 1.9.3 and same settings. I only want to see values.

**Comment by proddy** [comment]
and `info` shows.....?

**Comment by kkberg** [comment]
Boiler not enabled

**Comment by proddy** [comment]
well, there's your answer. no boiler = no data. Since 1.9.4 Tx is needed to send requests to each of the connected devices to identify them. Otherwise it has no idea of the model and type. The project supports many brands now. Just hook up Tx and it should work.

**Comment by kkberg** [comment]
okay, good to know and I've to connect Tx. Wasn't aware off that and wanted to make sure that nothe can happen accidently. But thank you very much and I'm sorry for my mistake.

**Comment by proddy** [comment]
You don't to worry. Tx is used only to send read "query" requests, not write requests so its harmless.

**Comment by kkberg** [comment]
I now have a lot of detailed information more than in the earlier version. I'm really very happy with it. Thank you again.

**Comment by proddy** [comment]
I will also look at the code and give a warning if Tx is not 'active'. I'm sure others will run into the same problem.
