### ISSUE TITLE
Enhancement: Support of mini OLED display attached to Wemos D1

### ISSUE THREAD

**Issue by giovanne123** [proddy/EMS-ESP#275]
Maybe nice to have, but support of mini OLED display attached to Wemos D1 would be fine. (e.g. [oled display](https://randomnerdtutorials.com/esp8266-0-96-inch-oled-display-with-arduino-ide/)
If I have attached a display to the Wemos it would be fine to display some information. Information maybe configurable (bus staus, heating status, ...).

**Comment by bbqkees** [comment]
You can use an OLED display on a second Wemos with f.i. ESP-Easy to send the parameters from your home automation to that display.

**Comment by proddy** [comment]
EMS-ESP on the ESP8622 is almost out of memory (96%) so adding this feature would most probably break it. It would be a nice addition to the ESP32 though.
