### ISSUE TITLE
Heating circuit wrong in 1.9.5b11 

### ISSUE THREAD

**Issue by MichaelDvP** [proddy/EMS-ESP#284]
Please change in _getHeatingCircuit  line 1373:   = to ==

 if ((EMS_RxTelegram->type == EMS_TYPE_RC35StatusMessage_HC1) || (EMS_RxTelegram->type = EMS_TYPE_RC35Set_HC1)) {

to 
 if ((EMS_RxTelegram->type == EMS_TYPE_RC35StatusMessage_HC1) || (EMS_RxTelegram->type == EMS_TYPE_RC35Set_HC1)) {

and the other cases.

**Comment by proddy** [comment]
oops, fixed in 1.9.5b12
