### ISSUE TITLE
Hidden SSID

### ISSUE THREAD

**Issue by ro-attu1** [proddy/EMS-ESP#293]
**Scenario**
ems-esp (default firmware) connects to an ap (raspberry hostapd). It works when the SSID ist broadcast, when the SSID is switched to hidden  (ignore_broadcast_ssid=1) ems-esp can't connct but activates interal AP instead.

**Question**
Should the ems-esp (V 1.9.4, also 1.9.3) be able to connect to a hidden WLAN (non broadcast SSID?)  
If yes, are there restrictions to wich characters the SSID may contain (apart from blanks)?
Is there any way to further debug the connection?

**Device information**
 EMS-ESP version 1.9.4
[FS] System config loaded (422 bytes)
[FS] Custom config loaded (201 bytes)
[WEB] Web server started
[SYSTEM] Free Heap: 24128 bytes initially | 4240 bytes used (17%) | 19888 bytes free (82%)
Warning! EMS bus communication disabled when Serial mode enabled. Use 'set serial off' to start communication.
[WIFI] Connecting to SSID: xyz1.23
[WIFI] Could not connect to xyz1.23
[WIFI] Creating access point
[WIFI] MODE AP
[WIFI] SSID  ems-esp
[WIFI] IP    192.168.4.1

**Comment by proddy** [comment]
It should work fine with a hidden SSID with all versions of EMS-ESP. Its what I use at home too for testing. The only error that we can get back from the internal WiFi libraries is that it failed. Does it work with any other ESP* apps you have?
