### ISSUE TITLE
Is my boiler compatible

### ISSUE THREAD

**Issue by Chuckame** [proddy/EMS-ESP#297]
Hi,
I'm really interested about this project because of my boiler company support tells to me "you cannot connect your boiler to iot world because of ISM1 interface", but this interface is compatible with this project!
But I don't know what I do search and how to get more specified informations... 
I've got a "ZBS 22/210S-3 MA23 Solar S0200", this reference means something to someone?

Thanks

**Comment by bbqkees** [comment]
Check the installation manual to see if it says something like 'EMS bus'.

**Comment by proddy** [comment]
You do need an ISM1 interface (http://documents.junkers.com/sitemap/document/id/6720615095)

**Comment by Chuckame** [comment]
The technical support said to me that I've got an ISM1 interface, it's enough to get this library working?

**Comment by Chuckame** [comment]
Found there is a Bosch Heatronic 3 bus compatible, but no EMS compatible... Maybe the same.
Someone has this Heatronic module?

**Comment by bbqkees** [comment]
What thermostat do you have?

**Comment by proddy** [comment]
Your Junkers works with HT3 (a variation of EMS+) so in theory it should work. I would just try it out and see for yourself and if not help contribute to the code to enhance it. You just need an interface board and they're cheap to make or available to buy from bbqkees

**Comment by glitter-ball** [comment]
> Found there is a Bosch Heatronic 3 bus compatible, but no EMS compatible... Maybe the same.
> Someone has this Heatronic module?

My Worcester-Bosch GreenStar 24i is using Junkers HT3 / EMS+ and works OK with EMS-ESP.

**Comment by Chuckame** [comment]
I saw on https://hotgoodies.nl/shop/ems/ems-bus-gateway-instructions.html, apparently from bbqkees website :
Boiler compatibility
The interface is electrically compatible with all Bosch brand boilers, heat pumps and devices that have an EMS, EMS+, EMS2, EMS Plus, Heatronic or Heatronic 3 interface.

**Comment by Chuckame** [comment]
> What thermostat do you have?

I have this one : https://www.destockage-habitat.com/saint_ouen-93400/regulation_a_programmation_hebdomadaire_avec_sonde_exterieure_un_circuit_elm_leblanc/648855

**Comment by Chuckame** [comment]
No it's an FR100, apparently compatible !

**Comment by proddy** [comment]
cool. it'll work. if it doesn't we'll make it work.
