### ISSUE TITLE
1.9.4 does show MM400 instead of RC30/Moduline 400 and does not see thermostat anymore.

### ISSUE THREAD

**Issue by frankhommers** [proddy/EMS-ESP#300]
After upgrading to 1.9.4 my RC30/Moduline 400 is not recognized.

This was 1.9.3:
![image](https://user-images.githubusercontent.com/7355878/72423533-b891e000-3784-11ea-9eca-780d47e2ff8a.png)

This is 1.9.4:
![image](https://user-images.githubusercontent.com/7355878/72423755-18888680-3785-11ea-9855-cf3048573927.png)

So the thermostat functionality is gone. I have downgraded tot 1.9.3 for now.

**Comment by Gert05** [comment]
This is a known issue, similar (or identical) to issue #262 
Solution is to downgrade (as you have done) or use the current beta (I'm currently using 1.9.5b3).

**Comment by proddy** [comment]
yes fixed in 1.9.5
