### ISSUE TITLE
second FR120 thermostat not fully recognized

### ISSUE THREAD

**Issue by tboschman** [proddy/EMS-ESP#316]
Hi,

I have 2 FR120 thermostats on a junkers system. Both are discovered but only one shows up as a thermostat.
This one is listed as thermostat and reports the settings:
`Junkers FR120 (Version:55.01 ProductID:191 DeviceID:0x10)`

This one does not report any values :
`Junkers FR120 (Version:55.01 ProductID:191 DeviceID:0x19)`

Is it possible that the DeviceID:0x19 is missing as thermostat type?

**Comment by proddy** [comment]
Currently the code only supports 1 single thermostat for reading and writing. You can set which one using the command `set master_thermostat <device id>` which is in release 1.9.5. There is already an enhancement to natively support more than one. It's not difficult to add, just on a long list of other feature requests.

**Comment by proddy** [comment]
fixed in v2
