### ISSUE TITLE
Bosch CT200 not discovered in FW 1.9.4 (using BBQkees D1 mini)

### ISSUE THREAD

**Issue by martynhr** [proddy/EMS-ESP#317]
Worcester/Bosch Greenstar 37CDI (2012) Boiler
Worcester/Bosch Easy Control CT200 Thermostat

Guy, relatively new to this so please bear with me.
Recently purchased a BBQKees Gateway Premium II for a bit more boiler info.

Home Assistant running prior to purchase and was using a Node MCU with 4 dallas Temp Sensors to monitor Boiler Temperatures. (Programmed with Arduino IDE

Initial setup was dead easy and EMS-ESP recognised the boiler and thermostat although I could not get and reading from the Thermostat. (FW version 1.9.2.)

Updated to 1.9.4 (to enable static ip config) and have now lost discovery of the Thermostat completely.
I have tried 1 , 2 and 3 (EMS, EMS+ and Junkers) Tx modes to no avail.
Listen mode is disabled

EMS Dashboard
![image](https://user-images.githubusercontent.com/53083817/73381604-eff0a880-42bd-11ea-9cda-c312384db89a.png)

System Status:
![image](https://user-images.githubusercontent.com/53083817/73381798-42ca6000-42be-11ea-84c4-dfe82eb6c263.png)

I have also tried FW 1.9.5b20 without success.
All Firmwares uploaded using Web Interface.
Any ideas?

**Comment by proddy** [comment]
Hi @martynhr and welcome. Could you try the latest 1.9.5 again and type `devices` and post the output and then the command `autodetect`. Let's see what is happening.

**Comment by martynhr** [comment]
Hi, Thanks for the reply, (fast)
I'm trying not to sound think, but, where do I type devices in the web interface? I don't see any command console. Sorry. Like i said, this is new to me.

**Comment by martynhr** [comment]
Ah, Telnet using Putty via USB I presume?

**Comment by proddy** [comment]
haha, no worries. Check out the Wiki https://emsesp.github.io/docs/#/

**Comment by martynhr** [comment]
Done:

![image](https://user-images.githubusercontent.com/53083817/73393032-e291e900-42d2-11ea-8014-4bfe60d221d5.png)

**Comment by martynhr** [comment]
Are these any use to you:

![image](https://user-images.githubusercontent.com/53083817/73393802-381ac580-42d4-11ea-9866-81c1c74315ee.png)

![image](https://user-images.githubusercontent.com/53083817/73393818-423cc400-42d4-11ea-808b-60d976ff9954.png)

**Comment by proddy** [comment]
I found the problem. It's happened before. I used to think all product IDs are unique but it turns out the Thermostat CT200 has the same ID (203) as the Buderus Logamax U122 and Junkers Cerapur. So its detecting your thermostat as another boiler!

I'll need to think on the best approach around this.

Also note writing doesn't work yet on the CT200. See #239

**Comment by martynhr** [comment]
Well done, OK well i'll leave that with you for now.
Just an idea, would it be worth somehow linking the CT200 ID to a selected country somehow?? As we dont have the Buderus and Junkers in the UK.

**Comment by bbqkees** [comment]
Bosch sells the same hardware in various countries under different brand names.

Perhaps it should be a check of device ID && product ID.

**Comment by proddy** [comment]
exactly, this is what I've started coding. The UBA Master is always on DeviceID 0x08 so I've separated this logic out to scan for boilers first and then the other devices (thermostats, solar modules etc)

**Comment by martynhr** [comment]
Good luck solving the problem. Let me know if you want me to test anything.

**Comment by proddy** [comment]
@martynhr see if 1.9.5b21 does the trick. https://github.com/proddy/EMS-ESP/releases/tag/travis-dev-build

**Comment by martynhr** [comment]
OK FW Updated to 1.9.5b21
Results: Using Tx1
![image](https://user-images.githubusercontent.com/53083817/73501731-b6539680-43be-11ea-94ed-309e0487bf4f.png)

**Comment by proddy** [comment]
Can you just stick to Telnet and send the output of devices & autodetect with verbose logging.

**Comment by rskallies** [comment]
As I own also a CT200 I'll provide my logs.  
[autodetect.txt](https://github.com/proddy/EMS-ESP/files/4141385/autodetect.txt)
[devices.txt](https://github.com/proddy/EMS-ESP/files/4141387/devices.txt)

**Comment by proddy** [comment]
thanks @rskallies . With those dumps I was able to find the error. Hopefully this b23 release is better.

**Comment by rskallies** [comment]
@proddy . Yes, it works now with b23. Great!

These device IDs are on the EMS Bus: 0x08 0x09 0x18
and 3 were recognized by EMS-ESP as:
 UBAMaster: Buderus GBx72/Nefit Trendline/Junkers Cerapur/Worcester Greenstar Si/27i (DeviceID:0x08 ProductID:123 Version:06.03)
 Controller: Controller (DeviceID:0x09 ProductID:152 Version:03.01)
 Thermostat: Bosch EasyControl CT200 (DeviceID:0x18 ProductID:203 Version:02.08)

**Comment by proddy** [comment]
great! if you find any other problems please reopen this issue.
