### ISSUE TITLE
Support for multiple EMS-ESP instances

### ISSUE THREAD

**Issue by proddy** [proddy/EMS-ESP#329]
One feature from this old [post](https://github.com/proddy/EMS-ESP/issues/155#issuecomment-517229596) was to have EMS-ESP register on a different EMS bus id. Now it's fixed to `0x0B` which is the Service Key. Possibilities which have been tested are:

`0x0A` - Handheld terminal
`0x0D` - Modem (KM200)
`0x0F` - Time module
`0x12` - External error module

I propose to make this configurable. So multiple boards/gateways can be used.

**Comment by bbqkees** [comment]
You could make it configurable, but in general you only need one Gateway per bus anyway.

**Comment by proddy** [comment]
I've implemented it anyway - was a fun test.  It's in b35
