### ISSUE TITLE
Version 1.9.5b41

### ISSUE THREAD

**Issue by PhillyGilly** [proddy/EMS-ESP#332]
Just uploaded latest firmware.
After auto re-boot there is no Dashboard screen and the version isn't shown in the menu.
Also  the update firmware menu it reported no internet connection.
![image](https://user-images.githubusercontent.com/56273663/75138342-e5210c00-56e1-11ea-9d46-451f6ceeb5b8.png)
I have rolled back to 1.9.5b38

**Comment by proddy** [comment]
just made a fix (was reported in #298) in b42. Hopefully that would have fixed the web issue

**Comment by PhillyGilly** [comment]
![image](https://user-images.githubusercontent.com/56273663/75140350-a04ba400-56e6-11ea-8ba1-f66697405ca3.png)
Updated using the espota.py and that's good.
I'm keep updating as I'm looking out for the rev to incorporate my code fragments from issue #267 :-)

**Comment by proddy** [comment]
I forgot about the SM200 !
