### ISSUE TITLE
WIP: Documenting available variables

### ISSUE THREAD

**Issue by VincentSC** [proddy/EMS-ESP#336]
To be able to describe tactics to find all variables and to describe where in all these telegrams to find these, step 1 is to list and describe them. I thought it would be best to use an issue for that, before creating a PR for the docs - I'm going to take my time for this. :)

I'll update this text while I'm getting more familiar with the code.

Variables are categorised per device. Some device can have multiple instances. Some variables are sent as HEX and some as decimals.

# Generic
These are the same for each of the device-types.

- version: hardware version of the device
- device_id: unique device ID
- product_id: 
- device_flags: 
- device_desc_p: name of the device
- detected: true/false

# EMS_Thermostat
- hc
- active
- mode
- day_mode
- summer_mode
- holiday_mode
- daytemp
- nighttemp
- holidaytemp
- heatingtype
- circuitcalctemp
- setpoint_roomTemp
- curr_roomTemp
- version

# EMS_Mixing

- hc
- flowTemp
- pumpMod
- valveStatus

# EMS_Boiler
- wWActivated
- wWSelTemp
- wWCircPump
- wWDesiredTemp
- wWComfort
- selFlowTemp
- curFlowTemp
- retTemp
- burnGas
- fanWork
- ignWork
- heatPmp
- wWHeat
- wWCirc
- selBurnPow
- curBurnPow
- flameCurr
- sysPress
- serviceCodeChar
- serviceCode
- extTemp
- boilTemp
- pumpMod
- burnStarts
- burnWorkMin
- heatWorkMin
- wWCurTmp
- wWStarts
- wWWorkM
- wWOneTime
- wWCurFlow
- UBAuptime
- heating_temp
- pump_mod_max
- pump_mod_min
- tapwaterActive
- heatingActive

# EMS_SolarModule
- collectorTemp
- bottomTemp
- pumpModulation
- pump
- EnergyLastHour
- EnergyToday
- EnergyTotal
- pumpWorkMin
- setpoint_maxBottomTemp

# EMS_HeatPump
- HPModulation
- HPSpeed

**Comment by proddy** [comment]
we'll continue to comment the logic in the code.
