### ISSUE TITLE
Typo in ui-lovelace.yaml

### ISSUE THREAD

**Issue by mrfixit1** [proddy/EMS-ESP#34]
I think there's an underscore missing in sensor.warm_water_3way_valve. Changing this to sensor.warm_water_3_way_valve fixed an "Entity not available: " error in my lovelace UI.

**Comment by proddy** [comment]
that's right! I saw this too with the upgrade to the recent Home Assistant 0.85. They changed the ways IDs are parsed. I will update the files.
