### ISSUE TITLE
mqtt-topic start enhance boottime [1.9.5b54]

### ISSUE THREAD

**Issue by giovanne123** [proddy/EMS-ESP#347]
1.9.5b54:

would be fine to enhance within the mqtt-topic "start" the boottime to also display the date, not only the time (to also now the date when the boart was booted)

```
topic: home/ems-esp/start
payload: {"version":"1.9.5b54","IP":"192.168.0.129","boottime":"21:35:39 CET "}
```

**Comment by proddy** [comment]
ok!

**Comment by proddy** [comment]
fixed in b55.

**Comment by proddy** [comment]
date time is shown in ISO 8601 format, to avoid people arguing about the format :-)

**Comment by giovanne123** [comment]
thanks working :-)
