### ISSUE TITLE
on a HA restart request a mqtt-publish for topic "start" from the EMS-ESP

### ISSUE THREAD

**Issue by giovanne123** [proddy/EMS-ESP#348]
Question, is it possible from HA on a HA restart to request a mqtt-publish for topic "start" from the EMS-ESP? If yes, how?

Because topic start is only published once on EMS-ESP booting/restarting.

If I have to restart HA because of an update, I currently have to reboot the EMS-ESP also to retrieve the start topic, otherwise I will stay with "Unknown" status within HA. 

(currently on EMS-ESP 1.9.5b54; HA 0.106.6)

**Comment by proddy** [comment]
I need to change the 'start' payload and set the MQTT retain flag, which means that message will always be present in the MQTT broker. I'll make the change now.

**Comment by giovanne123** [comment]
Thanks,
for my understanding, is the Retain Flag within the Web-UI meant or does this have a different meaning? I tried to play with it before ;-)

**Comment by proddy** [comment]
yes, similar but that setting is only for the specific EMS-ESP topics (like boiler, thermostat etc) and not for the system topics (like start, status)

**Comment by proddy** [comment]
fixed in b55.

**Comment by giovanne123** [comment]
thanks working :-)
