### ISSUE TITLE
telnet set command uses wrong characters

### ISSUE THREAD

**Issue by SpaceTeddy** [proddy/EMS-ESP#35]
to setup a new wifi connection via telnet I used the set wifi_ssid command.
Result: the set command ignores uppercases and modifies it to lowercases.
Currently I see no way to change from AP to Client mode. I had to flash back to 1.2.4.

![image](https://user-images.githubusercontent.com/9148964/51071166-f1b4e300-164c-11e9-8c3e-a00be22d0783.png)

kind regards,
chris

**Comment by proddy** [comment]
that is a silly bug, I lowercase all the telent commands. I'll fix that now, but you can still hardcode the wifi/mqtt settings in my_config.h

**Comment by SpaceTeddy** [comment]
Well, I tried to hardcode the new WiFi said, but for ever reason, the system tried to connect to the old ssid. Did you store the old settings anywhere? If yes, do you use these settings only?

**Comment by proddy** [comment]
they are stored in SPIFFS, the internal ESP's RAM which is like a file system. When you start type 'set erase' and this will reset all your settings and take the ones from my_config.h

**Comment by SpaceTeddy** [comment]
Alright. 😎

**Comment by SpaceTeddy** [comment]
fixed!
