### ISSUE TITLE
Working without temp sensor ?

### ISSUE THREAD

**Issue by Chuckame** [proddy/EMS-ESP#351]
**Question**
I just received the EMS interface board. According to documentation (https://emsesp.github.io/docs/#/Configure-firmware?id=hooking-up-the-interface-board), is it possible to run EMS-ESP without temperature sensor ?

For the moment, I just want to monitor my boiler, while the current thermostat working too.

**Comment by proddy** [comment]
Sure, just don't connect one. When EMS-ESP starts it will look for any Dallas type sensors attached to the board.
