### ISSUE TITLE
Debug for wifi connect  

### ISSUE THREAD

**Issue by muzixiaosanshi** [proddy/EMS-ESP#36]
Hi proddy:

I use linux enviroment to build code,when I finished build and upload firmware to ESP8266 board and press reset button on the board.I search IP on my router but I cann't found it connect to my router.I found board return to AP mode.I found in your wiki:
If the WiFi, MQTT, MDNS or something else fails to connect, re-build the firmware using the `-DDEBUG_SUPPORT` option.
So I use this command "sudo platformio --DDEBUG_SUPPORT run -t upload",but it cann't work.Does this command is right?

**Comment by muzixiaosanshi** [comment]
I config my wifi SSID and passwd in /src/myconfig.h

**Comment by muzixiaosanshi** [comment]
Hi proddy:
I forgot to tell you I have already configured wifi ssid and passwd in /src/my_config.h.I want to know why my board can't connect to my router.Thanks.

**Comment by proddy** [comment]
I don't think you did anything wrong. Default settings should start up in AP mode and should be visible as ems-esp on your router. I will need to do some more testing here to check that it works correctly on a non Windows environment.  If the wifi fails then you can't get telnet which is used for logging information which is why I in extreme situations you can use DEBUG_SUPPORT and then see the wifi connect details on the Serial USB. I've updated the doc to make this clearer

**Comment by muzixiaosanshi** [comment]
Hi proddy:
Thanks for your reply. If default setting is AP,how can 8266 connect to my router? And you mentioned above "should be visible as ems-esp on your router."I can't understand this,could you explain this clearly for me,Thanks.

**Comment by muzixiaosanshi** [comment]
Now,esp8266 is invisible on my router.So i want to rebuild firmware use debug_support to see log use usb serial.Thanks.

**Comment by muzixiaosanshi** [comment]
Hi proddy:
Thanks for your help,Now my ESP board can connect to my router.I found one

**Comment by muzixiaosanshi** [comment]
Hi Proddy:
Thanks for your help,my ESP can connect to my router.But I found one problem.I wonder you have ever met before.I found "set wifi_ssid [value]" value - must be lowercase letters.if I input capital ,I saw log print  corresponding lowercase letters.For example:My router name is "TP-LINK-E9EA",when I input "set wifi_ssid TP-LINK-E9EA".Log print "set wifi_ssid  tp-link-e9ea".So I change my router name from capital to lowercase letters,then it can connect sucessfully.

**Comment by proddy** [comment]
Yes, the lower case bug was fixed in the latest release

**Comment by proddy** [comment]
Yes it’s described step by step in my readme

**Comment by muzixiaosanshi** [comment]
Ok,I will read your readme carefully,Thanks.
