### ISSUE TITLE
Why i do not see vlues from ems-esp in homeassistant

### ISSUE THREAD

**Issue by pitulek** [proddy/EMS-ESP#367]
Hi!

i have a question , have problem with homeassistant.No values, all are unknown.Do not know the reason why? mqtt broker is working , ems-esp working.

/home/piotr/Pulpit/Zrzut ekranu z 2020-04-14 22-31-04.png

/home/piotr/Pulpit/Zrzut ekranu z 2020-04-14 22-35-22.png

/home/piotr/Pulpit/Zrzut ekranu z 2020-04-14 22-34-29.png

/home/piotr/Pulpit/Zrzut ekranu z 2020-04-14 22-35-10.png

**Comment by pitulek** [comment]
![Zrzut ekranu z 2020-04-14 22-31-04](https://user-images.githubusercontent.com/63159564/79271778-aa954d80-7ea0-11ea-8731-32aca8746bb3.png)
![Zrzut ekranu z 2020-04-14 22-35-22](https://user-images.githubusercontent.com/63159564/79271788-ae28d480-7ea0-11ea-80e8-9991d7b3a6c9.png)
![Zrzut ekranu z 2020-04-14 22-34-29](https://user-images.githubusercontent.com/63159564/79271792-aff29800-7ea0-11ea-8c46-e46894c4f060.png)
![Zrzut ekranu z 2020-04-14 22-35-10](https://user-images.githubusercontent.com/63159564/79271797-b1bc5b80-7ea0-11ea-9224-72f55b0716c5.png)

**Comment by bbqkees** [comment]
You need to enter the mqqt parameter in configuration.yaml:
`# Example configuration.yaml entry
mqtt:
  broker: IP_ADDRESS_BROKER`

**Comment by proddy** [comment]
Also, I check your EMS-ESP settings (in telnet or web). The format of MQTT topics are as default `/home/ems-esp/topic` where `home` is the MQTT base defined in EMS-ESP and the `ems-esp` is the hostname. This is also documented in the [wiki](https://emsesp.github.io/docs/#/MQTT). You can change these obviously but make sure you also change the .yaml files in Home Assistant.

Also use the latest 1.9.5b as it has many more improvements in the MQTT service code.

**Comment by pitulek** [comment]
Thank you very much, i have soleved it  by mayself earlier, ems-esp should be. not home/ems-esp.MQTT explorer is useful.
Proddy and bbqkees thank you very much for your help! You do great job.
I am new to this and try to understand how it all works.
