### ISSUE TITLE
1.9.5 MQTT topic - home/ems-esp/start

### ISSUE THREAD

**Issue by giovanne123** [proddy/EMS-ESP#378]
Within 1.9.5 (master), can it be that the MQTT topic: home/ems-esp/start isn't send or filled with old data after reboot/system start? 
Was introduced with #348 (retain flag)

Isn't updated for my currently ({"version":"1.9.5b58","IP":"192.168.0.129","boottime":"2020-04-15T18:36:52"})

Version 1.9.5 is display right within telnet and WebUI and other MQTT topics are send correctly.

**Comment by proddy** [comment]
strange. let me check...

**Comment by proddy** [comment]
I do get the start topic sent. If i delete it (using MQTT Explorer) and reboot EMS-ESP it pops up again. But I did notice the retain is not working as it should.

**Comment by giovanne123** [comment]
ok, I get the start topic also send after new subscribe and reboot.
But I still get old payload {"version":"1.9.5b58","IP":"192.168.0.129","boottime":"2020-04-15T18:36:52"}
instead of version: 1.9.5 or boottime: today's date&time
hm...

**Comment by giovanne123** [comment]
nothing changed but after testing again today and after restarting of everything (HA; EMS-ESP; MQTT republish; ...) now the start topic reports the right data ;-)
