### ISSUE TITLE
page requests fonts/glyphicons-halflings-regular.woff2

### ISSUE THREAD

**Issue by jandrassy** [proddy/EMS-ESP#403]
The web page requests `fonts/glyphicons-halflings-regular.woff2` from bootstrap-3.4.1.min.css, but there is firmware serves only `fonts/glyphicons-halflings-regular.woff` 

I want to fix it. Which way?

**Comment by proddy** [comment]
I'm not supporting version 1.9.x anymore as we prepare with for v2 with a new web UI. 

The woff2 issue is common (google it). It's not used by the application so no point downloading and adding. It's to do with the browser not recognizing the mime types.
