### ISSUE TITLE
(v2) Does not restore WiFi connection

### ISSUE THREAD

**Issue by sq4bja** [proddy/EMS-ESP#416]
Firmware A30 (and earlier) - after lost WiFi connection EMS-ESP cannot connect again. It flashing led quickly.

**Comment by FredericMa** [comment]
I've also seen this after rebooting my router but didn't look into it in detail yet.

**Comment by proddy** [comment]
yes, it's a known issue in v2 (and done intentionally) and something that will be resolved when I merge in the new web UI which I'm working on now
