### ISSUE TITLE
MQTT Message not complete

### ISSUE THREAD

**Issue by Chaot1** [proddy/EMS-ESP#42]
Thank you for the great work. It's perfect for me.

I have a smll problem that i can't solve:

When i look on directly on the esp i can read all values (semms correct) 
`info
EMS-ESP System setstats:
  System logging set to None
  LED is off
  # EMS type handlers: 36
  Thermostat is enabled, Boiler is enabled, Poll is disabled, Tx is enabled, Shower Timer is disabled, Shower Alert is disabled
  EMS Bus Stats: Connected=yes, # Rx telegrams=43, # Tx telegrams=57, # Crc Errors=0

Boiler stats:
  Boiler type: Sieger BK15 Boiler [TypeID 0x08] Product ID:64
  Hot tap water is off
  Central Heating is active
  Warm Water activated: on
  Warm Water circulation pump available: off
  Warm Water is set to Comfort
  Warm Water selected temperature: 60 C
  Warm Water desired temperature: 70 C
  Warm Water current temperature: 57.5 C
  Warm Water current tap water flow: 0.0 l/min
  Warm Water # starts: 6194 times
  Warm Water active time: 116 days 22 hours 40 minutes
  Warm Water 3-way valve: on
  Selected flow temperature: 75 C
  Current flow temperature: 73.1 C
  Return temperature: 70.0 C
  Gas: on
  Boiler pump: on
  Fan: on
  Ignition: off
  Circulation pump: off
  Burner selected max power: 123 %
  Burner current power: 25 %
  Flame current: 7.5 uA
  System pressure: 1.2 bar
  Current System Service Code: =H
  Outside temperature: 0.4 C
  Boiler temperature: 74.8 C
  Pump modulation: 100 %
  Burner # restarts: 51568 times
  Total burner operating time: 990 days 6 hours 44 minutes
  Total heat operating time: 873 days 8 hours 4 minutes
  Total UBA working time: 2666 days 13 hours 16 minutes

Thermostat stats:
  Thermostat type: Sieger ES73 [TypeID 0x10] Product ID:76
  Setpoint room temperature: 23.0 C
  Current room temperature: 22.8 C
  Thermostat time is 06:40:30 25/1/2019
  Mode is set to manual
`

but the MQTT message that i recieve is only this:
`{"wWSelTemp":"60",
"selFlowTemp":"65.0",
"outdoorTemp":"0.5",
"wWActivated":"on",
"wWComfort":"Comfort",
"wWCurTmp":"60.5",
"wWCurFlow":"0.0",
"wWHeat":"off",
"curFlowTemp":"57.9",
"retTemp":"48.7",
"burnGas":"on",
"heatPmp":"on",
"fanWork":"on",
"ignWork":"off",
"wWCirc":"off",
"selBurnPow":"100",
"curBurnPow":"50",
"sysPress":"1.2",
"boilTemp":"55.0",
"pumpMod":"100",
"ServiceCode":"-H"}`

How can i get the operating times?
It#s not very urgent, but id would be nice.

**Comment by proddy** [comment]
@Chaot1 only a selection of the values are published in the MQTT topic. This is to reduce the size of the messages (which is quite high now at 600kb) and also the traffic over the wifi which may interfere with the Rx/Tx due to signal noise and the mA drain. But it's easy to modify. One thing I was thinking is to split into smaller MQTT topics and making it configurable so you can select which values to send.

For the operating times, you can add these yourself with two lines to ems-esp.ino. Would you want the text like "873 days 8 hours 4 minutes" or a single value of the total minutes?

**Comment by Chaot1** [comment]
@proddy  Thank you for your fast response.
If possible i would like total minutes. So i can recalculate them on ioBroker.

You mean splitting like now the split into Boiler and Thermostat?
This would be a great idea. So everybody can select his preferred values and can reduce his MQTT traffic if not needed.
For me for example i don't really need and use the Thermostat values.

**Comment by Chaot1** [comment]
Ah ok,
now i Understand.
I put my desired values between Line 409 to 430 in the ems-esp.ino and delete what i don't need (fanwork or heatpmp for example because my boiler don't display it).

Is there any other position where i mus make some changes or ist it all?

**Comment by proddy** [comment]
that's correct, only need to change the lines in `publishValues()`

**Comment by Chaot1** [comment]
Thank you!
