### ISSUE TITLE
Missing telegram types for thermostat CW400

### ISSUE THREAD

**Issue by joanwa** [proddy/EMS-ESP#429]
edited for boiler->thermostat mixup

I have a CW400 thermostat with 1 heating circuit recognized as:
```
Thermostat: RC300/RC310/Moduline 3000/CW400/Sense II (DeviceID:0x10, ProductID:158, Version:18.06) ** master device **
 This Thermostat will respond to telegram type IDs: 0xA3 0x06 0x2A5 0x2B9 0x2A6 0x2BA 0x2A7 0x2BB 0x2A8 0x2BC 0x31D 0x31E
 Subscribed MQTT topics: thermostat_cmd cmd_temp cmd_mode cmd_temp cmd_mode cmd_temp cmd_mode cmd_temp cmd_mode
```
with three more missing telegram types:
```
000+15:39:19.677 D 42: [emsesp] No telegram type handler found for ID 0xBF (src 0x10, dest 0x00)
000+00:43:05.083 D 73: [emsesp] No telegram type handler found for ID 0xA2 (src 0x10)
000+00:08:32.915 D 275: [emsesp] No telegram type handler found for ID 0x267 (src 0x10, dest 0x00)
```
not really sure what it is, but what be happy to assist in encoding!

**Comment by proddy** [comment]
Both these are from the thermostat (device ID 0x10). 

I'm not sure what 0xBF is. I can't find any details on it and I usually use Norbert's guide for reference (https://github.com/norberts1/hometop_HT3/blob/master/HT3/docu/HT3-Bus_Telegramme.pdf) when it comes to Heatronics.

0x267 is an odd one. How many heating circuits are you using?

**Comment by joanwa** [comment]
just one heating circuit, but also using a mixing and a solar module MM100 & MS200. The Bosch Gateway is showing this:

![IMG_7252](https://user-images.githubusercontent.com/7691102/87959991-f36a2d00-cab3-11ea-9552-6069e26d0e43.PNG)
![IMG_7254](https://user-images.githubusercontent.com/7691102/87959998-f6651d80-cab3-11ea-8287-2717c166a1c5.PNG)

**Comment by norberts1** [comment]
@joanwa, @proddy : some information on that telegrams above, not yet in my documents but it will be as soon as possible.

![ID191_BF](https://user-images.githubusercontent.com/7714015/88710452-f948b980-d116-11ea-8896-d7d8cd03cf4f.png)
![ID162_A2](https://user-images.githubusercontent.com/7714015/88710500-06fe3f00-d117-11ea-9f59-44242786c417.png)
![ID615_0167](https://user-images.githubusercontent.com/7714015/88710510-0bc2f300-d117-11ea-8430-2e9a42150cb5.png)

**Comment by proddy** [comment]
thanks @norberts1 for describing those extra telegrams.

@joanwa is this information important to add to EMS-ESP? It's error status codes and floor drying status. I can add, but not sure if it's useful to report out in the WebUI or via MQTT.

Actually those screenshots you sent from the Bosch gateway look interesting. Is it just a mobile app? I'd love to be able to replicate that and show the same information. Do you think you could help collect some information on this

**Comment by joanwa** [comment]
@proddy those telegrams not actually needed. I'm still after the missing upper boiler and solar heat exchanger temperatures. Just posted all not recognized telegrams I've come across for the sake of completeness in pursuit of the missing temperatures.

Yes, thats the Bosch Easy Remote app. This app is just horrible. But if you want to replicate to show the same information, happy to help! They also do have a web login & interface from bosch, but I couldn't figure out how to get this to work. And believe it or not, local connection from the App to that gateway is only a feature for a year or so. Before everything had to go via Bosch servers.

**Comment by proddy** [comment]
great. If there is information which was useful to see in the Bosch app but missing now in EMS-ESP then lets try and add it.

**Comment by proddy** [comment]
Closing this. We determined the missing type_id's and not really worth picking up

**Comment by joanwa** [comment]
> great. If there is information which was useful to see in the Bosch app but missing now in EMS-ESP then lets try and add it.

I'm right now trying to figure out where the historical data for temperatures and energies are available. It's shown in both, app and controller. If I need help, will open a new issue.

![app_history_month](https://user-images.githubusercontent.com/7691102/92396720-c89c6c80-f125-11ea-80fd-7b8eb907fa84.png)
![app_history_week](https://user-images.githubusercontent.com/7691102/92396731-ccc88a00-f125-11ea-91a7-9d0c4f272faf.png)
![cw400_solar_history_last_week](https://user-images.githubusercontent.com/7691102/92396738-cfc37a80-f125-11ea-8cb1-e46136b0502c.jpg)
![cw400_solar_history_this_week](https://user-images.githubusercontent.com/7691102/92396739-d05c1100-f125-11ea-9b0c-0d521b65a248.jpg)
