### ISSUE TITLE
(V2) incorrect hostname shown in console (in system/show) when using static IP address

### ISSUE THREAD

**Issue by lmdecroos** [proddy/EMS-ESP#432]
When using a static IP address, then the hostname is correct in the webgui and syslog. 
But in the console the hostname is ESP-xxxxxx wheroff xxxxxx are the last 6 digits of the MAC address
MAC address: DC:4F:22:5E:96:9C
Hostname: ESP-5E969C

to reproduce:
go to wifi settings in the webgui
select static IP and provide the network settings
change the hostname to a name not starting with ems
restart the gateway
open telnet session
go to system
su
show

result the displayed hostname will be ESP-xxxxxx wheroff xxxxxx are the last 6 digits of the MAC address

tested on B5, B6 and B7

**Comment by proddy** [comment]
Thanks for reporting. I couldn't reproduce with B6 but will try again.

**Comment by proddy** [comment]
Ok, I reproduced this. The wifi hostname is not set when using a static IP so in `system` & `show` it will show the default one the ESP core gives you which is based on the MAC address. The console prompt is correct.
