### ISSUE TITLE
(V2) password for uploading the sofware over Wifi

### ISSUE THREAD

**Issue by lmdecroos** [proddy/EMS-ESP#433]
When uploading software over Wifi, the upload is password protected. Which is a good enhancement since V1.
But the password seems to be hardcoded.

To add more security the password for uploading over Wifi should be password of the admin user.

**Comment by proddy** [comment]
the OTA password is separately configured, only via the web under OTA Settings.

**Comment by lmdecroos** [comment]
Ok perfect!
Sorry that I didn’t spot this OTA setting in the web gui
