### ISSUE TITLE
(V2) how to set ems-esp/thermostat_cmd_mode for HC2 ?

### ISSUE THREAD

**Issue by lmdecroos** [proddy/EMS-ESP#444]
In version 1.9.5 we have  ems-esp/thermostat_cmd_mode1 for setting the mode of HC1 and  ems-esp/thermostat_cmd_mode2 for setting the mode of HC2.

In version 2.0  ems-esp/thermostat_cmd_mode is used to set the mode of HC1.
Is there a new mqtt syntax for setting the mode on HC2 ? 

MQTT message : ems-esp/thermostat_cmd_mode = day
000+00:11:30.893 I 11: [thermostat] Setting thermostat mode to day for heating circuit 1

**Comment by MichaelDvP** [comment]
`thermostat_cmd_mode` works on the first active hc. For other hc use the `thermostat_cmd` with
`{"hc2":{"mode":"day"}}` or `{"hc":2, "mode":"day"}` or `{"hc":2, "cmd":"mode", "data":"day"}`

**Comment by proddy** [comment]
spot on, thanks Michael. I will need to start working on updating the Wiki (https://emsesp.github.io/docs/#/MQTT) for v2

**Comment by lmdecroos** [comment]
Thanks for providing the new syntax.
It works from the mqtt explorer application
I'm waiting  until bbqkees has updated his domoticz plug-in for V2
