### ISSUE TITLE
(v2) RC20RF Error A01

### ISSUE THREAD

**Issue by SpaceTeddy** [proddy/EMS-ESP#454]
Dear all,
I'm perfectly happy with EMS-ESP V1 version, but I'm interested to play around with the new V2 and ESP32. 
During my quick test with V2 today I recognized, that V2 behaves different to V1 with my system configuration.
I found, that after some time (10min.), my RC20RF room thermostat shows Error *A01* on its display. I'm sure, that the room  temperature was shown correctly on the display and telnet console, but after a while, the RC20RF shows that error. 

With V1 I have following devices on the bus:  
```
These 5 were recognized by EMS-ESP:
 Boiler: Sieger BK13,BK15/Nefit Smartline/Buderus GB1x2 (DeviceID: 0x08, ProductID: 64, Version: 03.06)
 Controller: BC10/RFM20 Receiver (DeviceID: 0x09, ProductID: 68, Version: 02.03)
 Gateway: RC Remote Device (DeviceID: 0x18, ProductID: 94, Version: 02.01)
 Thermostat: RC20RF (DeviceID: 0x18, ProductID: 93, Version: 02.00)
 Thermostat: Sieger ES73 (DeviceID: 0x10, ProductID: 76, Version: 02.08) [master]
```

V2 show following devices:
```
ems-esp-2:/$ show devices
These EMS devices are currently active:

Boiler: BK13/BK15/Smartline/GB1x2 (DeviceID:0x08, ProductID:64, Version:03.06)
 This Boiler will respond to telegram type IDs: 0x10 0x11 0x18 0x19 0x34 0x1C 0x2A 0x33 0x14 0x35 0x15 0x16 0x1A 0xD1 0xE3 0xE4 0xE5 0xE9 
 Subscribed MQTT topics: ems-esp-2/boiler_cmd ems-esp-2/boiler_cmd_wwactivated ems-esp-2/boiler_cmd_wwonetime ems-esp-2/boiler_cmd_wwcirculation ems-esp-2/boiler_cmd_wwtemp 

Thermostat: ES73 (DeviceID:0x10, ProductID:76, Version:02.08) ** master device **
 This Thermostat will respond to telegram type IDs: 0xA3 0x06 0x3E 0x3D 0x48 0x47 0x52 0x51 0x5C 0x5B 0xA5 0x37 
 Subscribed MQTT topics: ems-esp-2/thermostat_cmd ems-esp-2/thermostat_cmd_temp ems-esp-2/thermostat_cmd_mode 

Gateway Module: RC20RF (DeviceID:0x18, ProductID:93, Version:02.00)
Controller: BC10/RFM20 (DeviceID:0x09, ProductID:68, Version:02.03)
```

shows for me, that V2 finds  the room thermostat RC20RF (DeviceID: 0x18, ProductID: 93, Version: 02.00) as  Gateway Module and and does not find the ProductID:94

Basically I have to use the ES73 as Master Thermostat, but for ever reason, the RC20RF is confused with V2.

Can you advice some tests I can do that the V2 find all devices correctly, or fixed that Error A01 behaviour?

btw: The esp8266 version behaves the same.

thanks a lot

EDIT: seems that V1 does not request data from ID 0x18. Is it possible to simply remove polling to 0x18 to see what happens?
  

some log:
```
000+00:16:33.707 D 2: [emsdevice] Received RC35Monitor
000+00:16:35.449 D 3: [emsdevice] Received UBAMonitorFast
000+00:16:35.763 D 4: [emsdevice] Received UBAMonitorWW
000+00:16:42.320 D 5: [emsdevice] Received RCTime
000+00:16:45.424 D 6: [emsdevice] Received UBAMonitorFast
000+00:16:45.664 D 7: [emsdevice] Received UBAMonitorWW
000+00:16:50.936 D 8: [emsdevice] Received RCOutdoorTemp
000+00:16:55.573 D 9: [emsdevice] Received UBAMonitorFast
000+00:16:55.849 D 10: [emsdevice] Received UBAMonitorSlow
000+00:16:56.081 D 11: [emsdevice] Received UBAMaintenanceStatus
000+00:16:56.287 D 12: [emsdevice] Received UBAMonitorWW
000+00:16:56.745 D 13: [emsesp] No telegram type handler found for ID 0x12 (src 0x10)
000+00:16:57.104 D 14: [emsesp] No telegram type handler found for ID 0x12 (src 0x10)
000+00:16:57.620 D 15: [emsesp] No telegram type handler found for ID 0x13 (src 0x10)
000+00:16:57.979 D 16: [emsesp] No telegram type handler found for ID 0x13 (src 0x10)
000+00:16:58.576 D 17: [emsesp] No telegram type handler found for ID 0xA2 (src 0x10)
000+00:17:00.018 D 18: [emsdevice] Fetching values for device ID 0x08
000+00:17:00.018 D 19: [telegram] Tx read request to device 0x08 for type ID 0x19
000+00:17:00.018 D 20: [telegram] Tx read request to device 0x08 for type ID 0x33
000+00:17:00.018 D 21: [telegram] Sending read Tx [#183], telegram: 0B 88 19 00 20 D0
000+00:17:00.018 D 22: [telegram] Tx read request to device 0x08 for type ID 0x16
000+00:17:00.018 D 23: [emsdevice] Fetching values for device ID 0x09
000+00:17:00.018 D 24: [emsdevice] Fetching values for device ID 0x10
000+00:17:00.018 D 25: [telegram] Tx read request to device 0x10 for type ID 0x06
000+00:17:00.018 D 26: [telegram] Tx read request to device 0x10 for type ID 0x3E
000+00:17:00.018 D 27: [telegram] Tx read request to device 0x10 for type ID 0x3D
000+00:17:00.018 D 28: [telegram] Tx read request to device 0x10 for type ID 0xA5
000+00:17:00.018 D 29: [telegram] Tx read request to device 0x10 for type ID 0x37
000+00:17:00.018 D 30: [emsdevice] Fetching values for device ID 0x18
000+00:17:00.248 D 31: [telegram] [DEBUG] Last Tx Read operation failed. Retry #1. sent message: 0B 88 19 00 20, received: 10
000+00:17:00.468 D 32: [telegram] Sending read Tx [#191], telegram: 0B 88 19 00 20 D0
000+00:17:00.716 D 33: [telegram] [DEBUG] Last Tx Read operation failed. Retry #2. sent message: 0B 88 19 00 20, received: 89
000+00:17:00.841 D 34: [telegram] Sending read Tx [#192], telegram: 0B 88 19 00 20 D0
000+00:17:00.899 D 35: [emsesp] Last Tx read successful
000+00:17:00.900 D 36: [emsdevice] Received UBAMonitorSlow
000+00:17:01.188 D 37: [telegram] Sending read Tx [#184], telegram: 0B 88 33 00 20 78
000+00:17:01.230 D 38: [emsesp] Last Tx read successful
000+00:17:01.230 D 39: [emsdevice] Received UBAParameterWW
000+00:17:01.438 D 40: [telegram] Sending read Tx [#185], telegram: 0B 88 16 00 20 EC
000+00:17:01.480 D 41: [emsesp] Last Tx read successful
000+00:17:01.480 D 42: [emsdevice] Received UBAParameters
000+00:17:01.661 D 43: [telegram] Sending read Tx [#186], telegram: 0B 90 06 00 20 6C
000+00:17:01.818 D 44: [emsesp] Last Tx read successful
000+00:17:01.818 D 45: [emsdevice] Received RCTime
000+00:17:02.059 D 46: [telegram] Sending read Tx [#187], telegram: 0B 90 3E 00 20 8C
000+00:17:02.208 D 47: [emsesp] Last Tx read successful
000+00:17:02.208 D 48: [emsdevice] Received RC35Monitor
000+00:17:02.407 D 49: [telegram] Sending read Tx [#188], telegram: 0B 90 3D 00 20 80
000+00:17:02.619 D 50: [emsesp] Last Tx read successful
000+00:17:02.619 D 51: [emsdevice] Received RC35Set
000+00:17:02.855 D 52: [telegram] Sending read Tx [#189], telegram: 0B 90 A5 00 20 D2
000+00:17:03.153 D 53: [telegram] [DEBUG] Last Tx Read operation failed. Retry #1. sent message: 0B 90 A5 00 20, received: 89
000+00:17:03.279 D 54: [telegram] Sending read Tx [#193], telegram: 0B 90 A5 00 20 D2
000+00:17:03.459 D 55: [emsesp] Last Tx read successful
000+00:17:03.460 D 56: [emsdevice] Received IBASettings
000+00:17:03.751 D 57: [telegram] Sending read Tx [#190], telegram: 0B 90 37 00 20 A8
000+00:17:03.824 D 58: [emsesp] Last Tx read successful
000+00:17:03.824 D 59: [emsdevice] Received WWSettings
000+00:17:15.275 D 60: [emsdevice] Received UBAMonitorFast
000+00:17:15.590 D 61: [emsdevice] Received UBAMonitorWW
000+00:17:25.226 D 62: [emsdevice] Received UBAMonitorFast
000+00:17:25.491 D 63: [emsdevice] Received UBAMonitorWW
000+00:17:33.960 D 64: [emsdevice] Received RC35Monitor
000+00:17:35.251 D 65: [emsdevice] Received UBAMonitorFast
000+00:17:35.516 D 66: [emsdevice] Received UBAMonitorWW
000+00:17:42.573 D 67: [emsdevice] Received RCTime
```

**Comment by proddy** [comment]
The RC20RF is strange. You will need to modify the platformio.ini file and compile with -DEMSESP_DEBUG so we can see which telegrams and coming in and what is being sent. Then I can add these to the test simulation and try and reproduce the bug.

the A01 error, I don't know. Let's fix the device allocation first.

**Comment by SpaceTeddy** [comment]
ok, I will do so tomorrow. 
well, there were some changes regarding the RC20 and heating circuits in the past probably one of these has to do with this. 
I use the RC20RF as remote to the es73 and there should be no need to read or write to this device ID. Anyhow, hopefully I can flash and log it tomorrow. 
... to which logging level I have to set the system?

**Comment by MichaelDvP** [comment]
It's a bit strange that also in v1 gateway and RC20RF has thes ame device_id 0x18. When ems-esp requests the version information from 0x18, which device replies? Both devices are in the device lib, but v2 now matches the device to gateway, but reads  the version and device description from the thermostat. 

In the log there is `000+00:17:00.018 D 30: [emsdevice] Fetching values for device ID 0x18` but sadly the log stops before the requests to 0x18 are sent. @SpaceTeddy can you do a longer log and also use `watch raw 18` to see the telegrams from/to the device. Also while logging/watching do a `scan devices` than we see what comes back to the version requests.

@proddy A01 can have different reasons, but for remote controll surly it's a ems-communication error (error code 816). 

(I suppose that the thermostat is also recognized and the RCTime fetch-request to the remote causes the error)

**Comment by proddy** [comment]
> ... to which logging level I have to set the system?
@SpaceTeddy In theory you set `log debug` and use the command `scan devices` from the console but I realize this doesn't show you very verbose information so I'll need to improve that. I'm away at the moment but when I'm back I'll push a new build which also contains Michael's last PR with nice fixes.

**Comment by SpaceTeddy** [comment]
Hi folks,

I can provide some log files today. Please not, that I have made two logs. a) switch on Heater and EMS-ESP at the same time; b) heater is running and EMS-ESP is reset by button.
```
a) 
[ems-esp-v2_log_working_till_error_heater_and_esp32_on_same_time.txt](https://github.com/proddy/EMS-ESP/files/5055789/ems-esp-v2_log_working_till_error_heater_and_esp32_on_same_time.txt)

b)
[ems-esp-v2_log_working_till_error_heater_on_esp32_reset.txt](https://github.com/proddy/EMS-ESP/files/5055790/ems-esp-v2_log_working_till_error_heater_on_esp32_reset.txt)
```

with my little knowledge I can see that, depends on the startup, the found devices are different. But both result in the error of the RC20RF remote. Logs are made till the Error occoures + some seconds.

Hope that helps.

Error of the RF20M shows: EMS-Bus Error:
<img width="515" alt="Bildschirmfoto 2020-08-11 um 10 49 34" src="https://user-images.githubusercontent.com/9148964/89877531-7fa5d680-dbc0-11ea-8d6d-b130e80c4db9.png">

**Comment by MichaelDvP** [comment]
> ┌──────────────────────────────────────────┐
│ EMS-ESP version 2.0.0b7                  │

There are more than 100 commits since that version. Please use the actual version (or wait for proddys next commit) 
It's possible that the A01-bus-errors are caused by the old uart and not by the gateway/thermostat mismatch. 

Without `watch` it's difficult to check the logs, but here  the gateway is detected:
`000+00:00:10.647 D 41: [emsesp] Adding new device with device ID 0x18 with product ID 94 and version 02.01`
and here the thermostat only updates the version-info of the gateway instead of registering a thermostat-device (the update loop in `EMSESP::add_device`)
`000+00:01:04.042 D 303: [emsesp] Updating details to already existing device ID 0x18`

**Comment by SpaceTeddy** [comment]
oh dear,
I've updated to the latest V2 commit and since 1h no errors and also stable device detection. I still watching to the RC20RF but I guess no action on your side is needed. If it runs for 24h, I will close this issue.

sry guys,
Chris
