### ISSUE TITLE
(V2) Disable onboard LED?

### ISSUE THREAD

**Issue by FredericMa** [proddy/EMS-ESP#463]
Is it also in V2 possible to disable the onboard LED?
The EMS-ESP is in a cabinet where nobody sees it so quite useless (minor) power consumption in that case.
Maybe give users the option to have it ON or OFF if all is OK?
In case of error, blinking is off course the preferred behavior.

**Comment by proddy** [comment]
Yes. Good suggestion. I'll add it as an option.

**Comment by proddy** [comment]
in b13.

**Comment by FredericMa** [comment]
Works like a charm. Thanks!
