### ISSUE TITLE
(v2) tapwater_active and heating_active interchanged?

### ISSUE THREAD

**Issue by papaloewe** [proddy/EMS-ESP#465]
Could it be that the two values of tapwater_active and heating_active are interchanged?

**Comment by proddy** [comment]
Could be. Works on my system (which I can only test) but there have been reports on other HT3 systems where the logic is slightly off. See #354

**Comment by proddy** [comment]
@papaloewe any ideas on how to progress here?

**Comment by papaloewe** [comment]
Sorry, but I don't really know what to do. I just found out that in my case the value for "heating_active" always changes during heating and hot water operation. So I can't tell the difference now, but that's not so bad.

**Comment by papaloewe** [comment]
I am sorry for late answer.
Yes, it works now for me.
Many thanks.
