### ISSUE TITLE
(v2) MQTT commands get mixed up with heating circuits

### ISSUE THREAD

**Issue by proddy** [proddy/EMS-ESP#478]
PetrDa reported:

> {"cmd":"wwonetime","data":"on"} now works. But I am struggling with other commands. The command { "cmd":"mode", "data":"manual", "hc":"2" } at ems-esp/thermostat_cmd works correctly. But the command { "cmd":"temp", "data":"23.5", "hc":"2" } at ems-esp/thermostat_cmd has no effect to set the thermostat temperature. I also tested various modification (values instead of strings, "seltemp" instead of "temp", etc. What I am doing wrong?

and did some tests and there is something going wrong with the heating circuit detection again. Perhaps related to https://github.com/proddy/EMS-ESP/issues/288#issuecomment-686439909

For example running the offline unit test with `test mqtt` I see the default heating circuit is 0 and not 1

```
000+00:00:00.010 D 103: [mqtt] [DEBUG] Received ems-esp/thermostat_cmd => {"cmd":"temp","data":22.56} (length 27)
000+00:00:00.010 D 104: [mqtt] [DEBUG] Calling command temp, value 22.55, id is default
000+00:00:00.010 W 105: [thermostat] Set temperature: Heating Circuit 0 not found or activated for device ID 0x18
```

**Comment by MichaelDvP** [comment]
Heating circuit 0 is `AUTO_HEATING_CIRCUIT` and fetch the first active hc. This works here with hc2 only, does this also work in test mode?
`{"cmd":"temp"` calls `set_temperature` with `Mode::AUTO` but not all thermostats have this mode, RC20_2 and Junkers_FR, at first look, will not set temperature.
