### ISSUE TITLE
mixing_data payload

### ISSUE THREAD

**Issue by PhillyGilly** [proddy/EMS-ESP#479]
My MM200 is configured to manage two hot water circuits ww1 and ww2 but the payload looks like its hc1 and hc2
mixing_data9 = {"type":"wwc","flowTemp":52.1,"pumpMod":6,"status":1}
mixing_data10 = {"type":"wwc","flowTemp":55,"pumpMod":0,"status":0}
This is pretty much where we were at the start of closed issue #299 which @MichaelDvP helped with.
Can we revisit split between hc1/hc2 an ww1/ww2?

**Comment by proddy** [comment]
Not sure I follow. What is broken exactly? Is the data shown in Telnet and Web correct? @MichaelDvP knows more about the mixing units that I do.

**Comment by MichaelDvP** [comment]
I see, data are correct, but the names are not adjusted. I'll do a PR.

**Comment by proddy** [comment]
@PhillyGilly all good now?

**Comment by PhillyGilly** [comment]
> @PhillyGilly all good now?

Yes. Thanks. As far as I can tell right now.
