### ISSUE TITLE
1.5.0 errors

### ISSUE THREAD

**Issue by SpaceTeddy** [proddy/EMS-ESP#48]
Hi proddy,
I did not update since 1.3.0, becasue for me it worked fine and for weeks.
Now, i updated to 1.5.0 and found the following items:

- does not compile with hardcoded wifi settings in platformio.ini

`Compiling .pioenvs/nodemcuv2/src/ems-esp.ino.cpp.o
/Users/Christian/Documents/development/Arduino/EMS-ESP-1.5.0/src/ems-esp.ino: In function 'vo
id setup()':
<command-line>:0:11: error: 'xxxxxxx' was not declared in this scope
/Users/Christian/Documents/development/Arduino/EMS-ESP-1.5.0/src/ems-esp.ino:1089:19: note: i
n expansion of macro 'WIFI_SSID'
myESP.setWIFI(WIFI_SSID, WIFI_PASSWORD, WIFICallback);

<command-line>:0:15: error: 'xxxxxxxxx' was not declared in this scope
/Users/Christian/Documents/development/Arduino/EMS-ESP-1.5.0/src/ems-esp.ino:1089:30: note: i
n expansion of macro 'WIFI_PASSWORD'
myESP.setWIFI(WIFI_SSID, WIFI_PASSWORD, WIFICallback);
^
*** [.pioenvs/nodemcuv2/src/ems-esp.ino.cpp.o] Error 1
`

- no MQTT update after flashing 1.5.0
- in telnet console, unknown command response if command is typed in. doesn't matter which command.
`Unknown command. Use ? for help.`

- since that update I get also errors on my Sieger BK15/ es73. -> EMS connection lost on my es73 / RC30 display. I guess that some items you change for RC10, it is not compatible to my system :(

For me, V1.4.0 was the best Version. Unfortunately I did not backup this version :( may you provide this Version to github?

thanks

**Comment by proddy** [comment]
ah sorry. I rushed it again. To use hardcoded wifi in platformio.ini use 
wifi_settings = '-DWIFI_SSID="XXXX"' '-DWIFI_PASSWORD="XXXX"'

I missed out the single quotes.

I'm looking into the other two issues now

**Comment by SpaceTeddy** [comment]
i updated also my post. Since this version, I get EMS connection errors on my es73/RC30 display. Sonething seems not compatible.
Do you have V1.3.0 still available? This is the best SW for me right now.

thx

**Comment by dutchrazor** [comment]
You can always download other versions by clicking on "Commits", https://github.com/proddy/EMS-ESP/commits/master , then click on the right most button. You then see the repo at that commit.

**Comment by SpaceTeddy** [comment]
@dutchrazor, great! good hint. thank you. that helps a lot

**Comment by proddy** [comment]
@SpaceTeddy there was a bug in 1.5.0 which i resolved the same day in 1.5.1. sorry for the inconvenience. There have been many improvements to the code since 1.3.0, in memory optimization and performance. bbqkees was shipping the firmware with his circuit boards (!!) so the code needed to be versatile enough for people to use without understanding C++ or platformio.

**Comment by SpaceTeddy** [comment]
well, unfortunately since 1.5.x my setup works not really stable. I get many restarts (mqtt start) and the mqtt  update is approx 10 minutes. I'm not sure why this happens, but yesterday I switched back to 1.4.x and everything works well. I'm going to try to find the root cause in the next days, but right now I have to stay with 1.4.x. ... which has all what I need... :)

**Comment by proddy** [comment]
That's worrying. Would you mind trying again with the latest 1.5.2? I did some exhaustive tests and pretty sure all the bugs have been ironed out. Does the ESP reset itself or are you seeing the MQTT disconnecting (TCP disconnect) and reconnecting. I did see that happen once but couldn't reproduce it. Typing 'set' should show you the MQTT settings and upgrading from one version to the next should handle the new settings. If in doubt do a 'set erase', connect via Serial and set the settings manually.

Thanks for helping out.

**Comment by SpaceTeddy** [comment]
Hi proddy,

don't know what happens yesterday, but after reflashing to the lastest version, rewrite the wifi settings ect, the systems works stable again. I guess the issue can be closed.
