### ISSUE TITLE
Telnet command to restart

### ISSUE THREAD

**Issue by glitter-ball** [proddy/EMS-ESP#488]
**Question**
Is there a text mode reboot/restart command under 2.0.1b4? Tried obvious things but didn't work. Would be handy when the web interface struggles. I tried to su with the password quoted in the upgrade notes but it didn't like that, alas. Thanks..

**Comment by glitter-ball** [comment]
OK. Found the restart command in the full command listing further down the New Features page.

But... the password `ems-esp-neo` doesn't work when I try and `su`.
```


┌──────────────────────────────────────────┐
│ EMS-ESP version 2.0.1b4                  │
│ https://github.com/proddy/EMS-ESP        │
│                                          │
│ type help to show available commands     │
└──────────────────────────────────────────┘

ems-esp:/$ su
Password:
su: incorrect password
000+00:10:37.356 N 0: [shell] Invalid admin password on console
ems-esp:/$
```

**Comment by proddy** [comment]
@glitter-ball if you upgraded from v1.9.5 this would have been the admin password.

**Comment by glitter-ball** [comment]
OK. Got it. All good. Thanks.
