### ISSUE TITLE
parasite Dallas sensors not working

### ISSUE THREAD

**Issue by JewelZB** [proddy/EMS-ESP#490]
In the latest 2.0.1 development build the dallas sensors seem to be not functioning.
The web interface states "No connected Dallas temperature sensors detected" and no MQTT data is observed for the sensors.

I have two sensors attached in parasite mode that worked fine in the 1.9.5 build.
In the syslog I  see "[sensors] Bus reset failed" messages.

**Comment by glitter-ball** [comment]
I have one sensor in 3-wire mode and it worked fine when I upgraded from 1.9.5 to 2.0.1b4. The MQTT payload changed so I had to tweak definition in HA, but that's not relevant to your issue.

Is the Dallas GPIO pin setting correct (14 on my system)? That stopped my sensor working when I first installed it.

**Comment by JewelZB** [comment]
Yes the sensors are connected to pin 14, and the setting is on pin 14.
Rolling back the firmware to 1.9.5 fixes the problem for now.

**Comment by MichaelDvP** [comment]
Dallas parasite-mode has to be acivated, but this setting is missing in the actual build.

**Comment by proddy** [comment]
we need to add parasite back then?

**Comment by JewelZB** [comment]
I checked the code and Parasite mode seems to be missing altogether from the new sensors.cpp.
Yes it would be great to have parasite mode back in 2.0.
I already tried adding it myself but ran into some problems with the way sensors.cpp communicates with the sensors (seems to be designed to support hotplugging?) so need to dig further.

**Comment by MichaelDvP** [comment]
I checked how parasite works and the 1.9.5 code, it is not a big deal in the software. I can add the parasite setting, but can not test, i have not such a sensor. @proddy should i make a pr?

**Comment by MichaelDvP** [comment]
@JewelZB if you want to try and compile your own, i think all you have to do is in `sensor.cpp`
Line 70: `bus_.write(CMD_CONVERT_TEMP, 1);`
Line 80: `if (time_now - last_activity_ > CONVERSION_MS) {`
(skip the complete-check, it does not work in parasite mode)
than this is fixed setting to parasite on.

**Comment by JewelZB** [comment]
@MichaelDvP , thanks for the quick reply! I hope i can find a moment to try it out this weekend!

**Comment by proddy** [comment]
I have a few parasite DS18b20's lying around so will also test this weekend
