### ISSUE TITLE
Migrate Travis CI to GitHub actions

### ISSUE THREAD

**Issue by proddy** [proddy/EMS-ESP#498]
GitHub Actions is quite nice and if we move the CI process (automatic code checking, building firmware versions) directly to the repo it will save on using external applications (travis and having a separate build bot GitHub account) and enable all main contributors to tweak the settings. Other workflows could be added too, such as running some of the unit tests and simulating different devices.

**Comment by proddy** [comment]
done. On push and pull in the dev branch the firmware builds are checked and created and binaries moved to https://github.com/proddy/EMS-ESP/tree/firmware/firmware

**Comment by proddy** [comment]
looking into whether we can create github actions to build releases on tag commits and also nightly builds. Adding binary artifacts to the 'firmware' branch is not optimal.

**Comment by proddy** [comment]
Dev builds are created when the file CHANGELOG_DEV.md is updated and the release is at https://github.com/proddy/EMS-ESP/releases/tag/dev

**Comment by proddy** [comment]
build is triggered when `CHANGELOG_LATEST.md` is pushed.

Also create a script to build the official stable release from the `main` branch.

@MichaelDvP I'd like to get 2.1 out to everyone. bbqkees needs it for his next batch of gateways. And the mismatch between the documentation and 2.0.1 is confusing people. When you've done the NTP month+1 fix shall we make the next stable release? or would you rather wait to finish up some other issues?

**Comment by MichaelDvP** [comment]
I think it's a good time for a new release. With the latest changes i'm not sure about the thermostat 0xBF. I thought it is on RC300 instead of A2 and used the same value, but now it seems both telegrams are present in RC300. Remove 0xBF? I think publishing 2 error-messages from the same device is to much, errors are very rare.

**Comment by proddy** [comment]
agree, let's leave 0xBF for now.

**Comment by MichaelDvP** [comment]
Ok, i remove it from thermostat.
