### ISSUE TITLE
wrogn admin password

### ISSUE THREAD

**Issue by cyniu88** [proddy/EMS-ESP#504]
after put "su" command in console the only one good password is "ems-esp-neo" not default "admin"

release  2.0.1

> 

> iDom-client/buderus/ems-esp:/boiler$ su
> Password:
> su: incorrect password
> 000+00:54:34.821 N 1: [shell] Invalid admin password on console
> iDom-client/buderus/ems-esp:/boiler$ su
> Password:
> 000+00:54:59.680 N 2: [shell] Admin session opened on consol

e

**Comment by proddy** [comment]
RTFM

"`su` will switch to the Admin super-user. The default password is **ems-esp-neo** and can be changed with `passwd` from the system menu or via the Web interface (called secret password). When in Admin mode the command prompt switches from `$` to `#`."

https://github.com/proddy/EMS-ESP#using-the-console
