### ISSUE TITLE
MQTT retained message

### ISSUE THREAD

**Issue by cyniu88** [proddy/EMS-ESP#507]
is it possible to return the flag "retained" in MQTT settings as in 1.9.5 ?

**Comment by proddy** [comment]
Can do. What's the use case you had in mind?

**Comment by cyniu88** [comment]
I create my own application to view data and configure my boiler and after connecting to the mqtt broker I have to wait for the boiler to send a message. And for this short moment (at worst 10 seconds) I only see "0" :) Hope you understand my case when you take the phone and check the tap temperature it takes less than 3 seconds if messages are retained.

**Comment by cyniu88** [comment]
I know there are many tricks to fix this but the mqtt retain flag seems to be the best

**Comment by proddy** [comment]
Ok. Have you played with the publish interval setting?

**Comment by cyniu88** [comment]
yes, but a small interval generates a lot of traffic on the broker, in my opinion it is better to avoid huge traffic.

**Comment by proddy** [comment]
in 2.0.2
