### ISSUE TITLE
Update Domoticz plugin for EMS-ESP v2.1

### ISSUE THREAD

**Issue by proddy** [proddy/EMS-ESP#526]
The previous Domoticz plugin for EMS-ESP v1.9.5 is no longer compatible with all the changes in v2.1.

@Gert05 has been working on new version. Would you mind sharing it so I can include the link in the EMS-ESP Documentation. And we can keep this GitHub issue open to collect feedback.

thanks

**Comment by bbqkees** [comment]
The Domoticz plugin is still functional for the most part except for the thermostat topics.
https://github.com/bbqkees/ems-esp-domoticz-plugin.
We should not create two separate plugins.

**Comment by Gert05** [comment]
Attached the updated plugin.py.

It provides a basic interface in Domoticz: read room temperature & system pressure, change thermostat temperature.

Plugin.py goes into a “nefit” directory in /home/pi/domoticz/plugins (on a raspberry pi).

It also needs an mqtt.py; this is unchanged from the previous version.

Tested on Domoticz 2020.2 (12125) & EMS-ESP v2.0.1b4.

 

Van: Proddy <notifications@github.com> 
Verzonden: dinsdag 29 september 2020 17:16
Aan: proddy/EMS-ESP <EMS-ESP@noreply.github.com>
CC: Gert05 <gert.boer@gmx.net>; Mention <mention@noreply.github.com>
Onderwerp: [proddy/EMS-ESP] Update Domoticz plugin for EMS-ESP v2 (#526)

 

The previous Domoticz plugin for EMS-ESP v1.9.5 is no longer compatible with all the changes in v2.0.

@Gert05 <https://github.com/Gert05>  has been working on new version. Would you mind sharing it so I can include the link in the EMS-ESP Documentation. And we can keep this GitHub issue open to collect feedback.

thanks

**Comment by proddy** [comment]
missing attachment !

**Comment by Gert05** [comment]
Noticed that. Struggling with GitHub…

 

Van: Proddy <notifications@github.com> 
Verzonden: woensdag 30 september 2020 12:58
Aan: proddy/EMS-ESP <EMS-ESP@noreply.github.com>
CC: Gert05 <gert.boer@gmx.net>; Mention <mention@noreply.github.com>
Onderwerp: Re: [proddy/EMS-ESP] Update Domoticz plugin for EMS-ESP v2.1 (#526)

 

missing attachment !

**Comment by proddy** [comment]
Could you include a small README on how to install/use. Then I'll also add it to the dev branch and include a link in the Documentation. Also make sure it works with 2.1 where the topic names have changed (e.g. from thermostat_cmd to thermostat).

**Comment by proddy** [comment]
thanks!
