### ISSUE TITLE
Connection issue - Tx errors

### ISSUE THREAD

**Issue by czykwin** [proddy/EMS-ESP#541]
@bbqkees I've just connected brand new gateway for the first time and it's not working.
No EMS devices found. 129 (Rx) Incomplete telegrams and growing (0 others).
Connected by service jack to the Buderus GB072 (with Logamatic webKM200 and Logamatic RC300).
I've no idea what is wrong, please help.

**Comment by czykwin** [comment]
v2.0.1
![image](https://user-images.githubusercontent.com/72528759/95458010-eb62b080-0971-11eb-9b61-23869a7b205b.png)
![image](https://user-images.githubusercontent.com/72528759/95458058-fcabbd00-0971-11eb-9fe9-e33035f089dd.png)

**Comment by bbqkees** [comment]
Hi,
Can you open the Gateway, remove the white plastic side of the jack connector and reinsert the plug?
Some of the cables I got recently have a very slightly thicker plug and do not fit properly in the recessed hole in front of the jack causing the plug to misalign and not make proper contact.

**Comment by czykwin** [comment]
The housing was not twisted at all, I enlarged the jack hole and now it's ok :)
