### ISSUE TITLE
Remove MQTT topics heating_active and tapwater_active

### ISSUE THREAD

**Issue by proddy** [proddy/EMS-ESP#543]
Originally I used individual MQTT topics for signaling whether the heating and/or hot water was on or off. This was to allow Boolean sensors in Home Assistant. Now with the latest HA MQTT Discovery implemented this data is already captured in the `boiler_data` topic and picked up as a separate entity. 

Ok to remove it? Anyone using it?

@MichaelDvP @bbqkees

**Comment by bbqkees** [comment]
This is a duplicate of #542

**Comment by proddy** [comment]
i had gity-hub glitches. removing.
