### ISSUE TITLE
measure temperature after update fw to v2.1.0b6 to not work

### ISSUE THREAD

**Issue by Bartekn86** [proddy/EMS-ESP#545]
Hi, 
after update fw to b6 temperature measuring ftom boiler do not want to refresh. showing static temperature gb072v2 (domoticz)
Warm water storage temperature in ems-esp websit shows ok 
Please help, 
thank you

**Comment by proddy** [comment]
from which version did you upgrade from? Which version of the domoticz plugin are you using? Do you see the values changing in the console, web and MQTT? Please be more specific so we can help

**Comment by Bartekn86** [comment]
upodated from b3  domoticz plugin latest dev-2, value changing in web, (dont know how to check console or mqtt).

**Comment by MichaelDvP** [comment]
Ah, seems the same rename problem i get a few days ago in my scripts: `wWCurTmp` is now corrected to `wWCurTemp`. 
@bbqkees: can you adapt this in [your plugin](https://github.com/bbqkees/ems-esp-domoticz-plugin/blob/master/plugin.py)

**Comment by Bartekn86** [comment]
MichaelDvP thank you for your time and help :-)

**Comment by bbqkees** [comment]
@MichaelDvP Yes I got a few comments on that one already. Had it changed locally for the next update but I'll change it right away in the repository.
