### ISSUE TITLE
outdoorTemp not reported anymore in 2.0.1

### ISSUE THREAD

**Issue by frankhommers** [proddy/EMS-ESP#547]
I don't see outdoorTemp anywhere anymore in MQTT since v2.0.

Through syslog I see that EMS-ESP receives it:
```
Time: Oct 10 15:09:09
Host: 1
Facility: logalert
Priority: debug
Message: [emsesp] Received RCOutdoorTemp
```

But that doesn't end up in a MQTT message anywhere.

![image](https://user-images.githubusercontent.com/7355878/95655938-1df3e100-0b0b-11eb-94e9-aa837e9f2485.png)

![image](https://user-images.githubusercontent.com/7355878/95655943-306e1a80-0b0b-11eb-96ca-ddb7487b10bb.png)

**Comment by proddy** [comment]
Can you try 2.1. Now all values are both in web and MQTT

**Comment by frankhommers** [comment]
Do you mean 2.0.1? This is what I was using... Or else: When can I get the 2.1 binary? :-P

**Comment by proddy** [comment]
It's in https://github.com/proddy/EMS-ESP/tree/firmware

I'm planning to release 2.1 soon, also with the update documentation
