### ISSUE TITLE
HA -  incorrect value of the sensor.nofrost_temperature 

### ISSUE THREAD

**Issue by majdzik84** [proddy/EMS-ESP#549]
**In home assistant, sensor.nofrost_temperature is entered as half the correct value**

![Zrzut ekranu 2020-10-10 205104](https://user-images.githubusercontent.com/31352476/95662888-7b535680-0b3a-11eb-8c6b-43f1099f6d84.png)

**Let me write on the same topic. I hope that this is not a problem.**

I also noticed that the HA detected the EMS-ESP Mixing entities, however the status is unknown

![image](https://user-images.githubusercontent.com/31352476/95662914-bc4b6b00-0b3a-11eb-9508-0eabc7c54025.png)

**Comment by proddy** [comment]
thanks for reporting, we'll look into it.

**Comment by proddy** [comment]
@MichaelDvP the code assumes the `nofrosttemp` value is *2, except in the RC35 it takes *1.

https://github.com/proddy/EMS-ESP/blob/ab3e4731a4a2a2a2eb98640fff98f0f0e23360b5/src/devices/thermostat.cpp#L1232

**Comment by proddy** [comment]
@majdzik84 for the mixing entities can you send what the MQTT payloads look like (use MQTTExplorer). In our tests it works. Also in HA the mixing values are sent to a separate homeassistant device so check the values there too (HA->Configuration->Devices->EMS-ESP Mixing)

**Comment by majdzik84** [comment]
@proddy I am uploading screenshots. I see values ​​in mqtt explorer but not in HA. I tried to remove the device and the topic was still in the same form.

![image](https://user-images.githubusercontent.com/31352476/95674306-957b4c00-0baf-11eb-9114-c4b9afd50587.png)

![image](https://user-images.githubusercontent.com/31352476/95674269-53520a80-0baf-11eb-8d3d-e22d01205577.png)

**Comment by proddy** [comment]
thanks. I think I know where the problem is now.

**Comment by MichaelDvP** [comment]
>  the code assumes the nofrosttemp value is *2, except in the RC35 it takes *1.

Right, Junkers is *2, RC35 is *1, settings are all ok, we need only change `export_values_hc` to:
```
            // Nofrost temperature
            if (Helpers::hasValue(hc->nofrosttemp)) {
                if (flags == EMSdevice::EMS_DEVICE_FLAG_JUNKERS) {
                    dataThermostat["nofrosttemp"] = (float)hc->nofrosttemp / 2;
                } else {
                    dataThermostat["nofrosttemp"] = hc->nofrosttemp;
                }
            }
```

The mixing is due to publish topic. The values are published as `mixing_data2`, but the HA-config sets `mixing_data`  in stat_t:
```
{"name":"Setpoint flow temperature","uniq_id":"mixing_flowSetTemp","unit_of_meas":"°C","stat_t":"ems/mixing_data","val_tpl":"{{value_json.flowSetTemp}}","ic":"mdi:coolant-temperature","dev":{"ids":["ems-esp-mixing"]}}
```
But change the register_HA is a lot of work, maybe it's easier to make a nested mixing_data with combined devices as in api-info.

BTW: But mixing is the only HA-config that uses hostname (here `ems`), all other configs are fixed to `ems-esp`, this could also make problems.

**Comment by proddy** [comment]
> But change the register_HA is a lot of work, maybe it's easier to make a nested mixing_data with combined devices as in api-info.

Nested is going to hard too because each unit is a separate device (instance class in EMS-ESP). Which makes me think there could be multiple mixings devices in HA. I need to think about this.

> BTW: But mixing is the only HA-config that uses hostname (here ems), all other configs are fixed to ems-esp, this could also make problems.

good point. Forgot about that. I'll make a change.

**Comment by MichaelDvP** [comment]
> Nested is going to hard too because each unit is a separate device 

I think it's easy, since it is in for api-info. The json for nested mixers has to be declared and published in emsesp- publish_device_values and call export_values to fill the nests. For single format call publish_values() for each device instead.

**Comment by proddy** [comment]
> I think it's easy, since it is in for api-info. The json for nested mixers has to be declared and published in emsesp- publish_device_values and call export_values to fill the nests. For single format call publish_values() for each device instead.

yes, that would work.  If the format is nested moved the publishing out of mixing.cpp to emsesp.cpp. You'll need to do some clever logic in process_telegram() to keep it clean.

**Comment by MichaelDvP** [comment]
I've pushed a first test my repo, compiles but not all tested yet. Take a look.

**Comment by proddy** [comment]
@MichaelDvP looks good. I tested and works fine as well. I would have implemented it the same way. The `JsonObject dummy` is not pretty but I couldn't find a nicer way either. So good to go.

**Comment by proddy** [comment]
now in 2.1.0b7. Thanks again Michael.

**Comment by proddy** [comment]
@MichaelDvP just did another test and I'm not seeing the nested values. But I'm using the standalone version to test (no ESP8266) so I could be my setup. One thing to note is that we need to make sure each Mixing device is independently created in Home Assistant. Now they will be overwritten as they are both have the same unique_ids (mixing).

**Comment by majdzik84** [comment]
EMS-ESP-2_1_0b7

![image](https://user-images.githubusercontent.com/31352476/95682740-43561d00-0be7-11eb-953a-c101ce9c3b1b.png)
![image](https://user-images.githubusercontent.com/31352476/95682761-67b1f980-0be7-11eb-82bc-6bf849f34b82.png)

**Comment by proddy** [comment]
@majdzik84 in MQTTExplorer can you show the value of the topics homeassistant/sensor/ems-esp/mixing*

**Comment by majdzik84** [comment]
![image](https://user-images.githubusercontent.com/31352476/95683287-92518180-0bea-11eb-8394-b4cbae3dfdad.png)

![image](https://user-images.githubusercontent.com/31352476/95683293-9a112600-0bea-11eb-8a43-7e2ed49e016d.png)

![image](https://user-images.githubusercontent.com/31352476/95683296-a09f9d80-0bea-11eb-96a0-d76fd69df801.png)

**Comment by MichaelDvP** [comment]
I've made some changes and pushed to my repo, but i'm not very familiar with HA. Does this look right?
![mqtt_ha_mixing](https://user-images.githubusercontent.com/59284019/95683459-a6e24980-0beb-11eb-8ae9-04e9e08fa9a0.png)

**Comment by proddy** [comment]
yes. the val_tpl needs to match the nested format in mixing_data. Before mixing_data was using hc1 and the HA config topics were using wwc2

**Comment by MichaelDvP** [comment]
@majdzik84 I think nofrost is ok and mixing mqtt is also ok now. Have you checked the HA config? If it works, close this issue.

**Comment by majdzik84** [comment]
Yes, the values ​​from my mixer showed up. I did not pay attention to them because more entities appeared. Well done. Thank you.


![image](https://user-images.githubusercontent.com/31352476/95837335-ca6ad880-0d40-11eb-9dcb-701f2622cfd8.png)
