### ISSUE TITLE
HA - binary_sensor.heating_active not working

### ISSUE THREAD

**Issue by majdzik84** [proddy/EMS-ESP#553]
I'd like to report that binary_sensor.heating_active  unfortunately it does not change the state in HA. Always shows off
![Zrzut ekranu 2020-10-12 102111](https://user-images.githubusercontent.com/31352476/95723170-210ae080-0c75-11eb-9130-79cd835fa582.png)

![image](https://user-images.githubusercontent.com/31352476/95723468-7941e280-0c75-11eb-937d-62c5ef9681f4.png)

**Comment by proddy** [comment]
I noticed that too and fixed it during the weekend. At least I think I did. Are you on the latest dev build, b7?

**Comment by majdzik84** [comment]
Yes, I have the latest version 2.1.0b7

**Comment by MichaelDvP** [comment]
I'm not sure and have no HA to test. But the mqtt is `heating_active = on` and the configuration is `"payload_on": "on"` with quotation marks. I didn't find exact information about configuration of binary sensors, but i read that binary sensors will react on on/off, true/false and 1/0, What happen if you skip the `payload_` from config and leave it to HA to interprete the value?

**Comment by MichaelDvP** [comment]
Since these are the only binary sensors and not working i tried to remove the "payload"-setting from config. 
@majdzik84 please give feedback if it's working or give errors, than i revert this.

**Comment by majdzik84** [comment]
I must apologize to you very much. The corrected version does not work. The previous one works for it! (SORRY) so you should undo the change. HomeAssistant created a second sensors (binary_sensor.heating_active_2) that I had not noticed before.

![image](https://user-images.githubusercontent.com/31352476/95896154-198a2b00-0d8c-11eb-9d57-38f5e67276e9.png)

**Comment by MichaelDvP** [comment]
Ok, change undone.
