### ISSUE TITLE
Bosch Condens 2500 - what protocol are use?

### ISSUE THREAD

**Issue by vampywiz17** [proddy/EMS-ESP#555]
Hello there,

If use this boiler with external thermostat (Tado), what protocol are we use?

The Options:

![image](https://user-images.githubusercontent.com/14281430/95846280-8c26e680-0d4b-11eb-9c84-b845304ec277.png)

The official manual say that it EMS, but no detailed info... This issue say that is HT3 (https://github.com/proddy/EMS-ESP/issues/39)

It possible that this boiler use EMS2? Unfortuantelly EMS2 is not supported by Tado.

**Comment by bbqkees** [comment]
I don't think its EMS2 but I'm not a Bosch dealer so better call one to verify.

**Comment by MichaelDvP** [comment]
@vampywiz17: start terminal and type `watch on 8`, if you see a type-id with 3 digits it's ems+, but i think most boilers are ems or HT3.  (i.e. the 3. number  => (0x34) in `Boiler(0x08) -> (0x00), (0x34), data: ...`)

**Comment by vampywiz17** [comment]
Success, it working with D17 (HT-Bus)

**Comment by proddy** [comment]
great!
