### ISSUE TITLE
Problem with new v2.0.1 .I can't send new temp , change mode.

### ISSUE THREAD

**Issue by pitulek** [proddy/EMS-ESP#561]
Hi, i cannot change temp , mode values in thermostat.In console always is too many arguments.Mqtt does not working too thermostat_cmd_temp1.
![Screenshot 2020-10-16 16:23:23](https://user-images.githubusercontent.com/63159564/96271883-b8ea3080-0fcd-11eb-9a5a-e74917aa53b5.png)

*Before creating a new issue please check that you have:*

* *searched the existing [issues](https://github.com/proddy/EMS-ESP/issues) (both open and closed)*
* *searched the [wiki help pages](https://bbqkees-electronics.nl/wiki/gateway/troubleshooting.html)*

*Completing this template will help developers and contributors help you. Try to be as specific and extensive as possible. If the information provided is not enough the issue will likely be closed.*

*You can now remove this line and the above ones. Text in italic is meant to be replaced by your own words. If any of the sections below are not relevant to the issue (for instance, the screenshots) then you can delete them.*

**Question**
*A clear and concise description of what the problem/doubt is.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Device information**
*Copy-paste here the information as it is outputted by the device. You can get this information by from the telnet session with the logging set to Verbose mode.*

**Additional context**
*Add any other context about the problem here.*

**Comment by proddy** [comment]
Take a look at https://emsesp.github.io/docs/#/Troubleshooting?id=some-commands-via-mqtt-are-not-working

Basically, use the Console with debug logging to see what is happening to trace where it is failing. Also recommend you upgrade to the latest 2.1 version which has many fixes in this area.

**Comment by pitulek** [comment]
i did it su
call thermostat temp 15 
command not found
![Screenshot 2020-10-16 16:59:26](https://user-images.githubusercontent.com/63159564/96274944-6579e180-0fd1-11eb-8925-70958daa9ef8.png)

**Comment by pitulek** [comment]
where i can download the other versions?

**Comment by MichaelDvP** [comment]
@pitulek i think you are not in su mode. Read [https://github.com/proddy/EMS-ESP#using-the-console](https://github.com/proddy/EMS-ESP#using-the-console)
The 2.1.beta firmware is [here](https://github.com/proddy/EMS-ESP/tree/firmware/firmware)

**Comment by pitulek** [comment]
Thank you for your help. It change the firmware and it is working from console with command "call thermostat nighttemp 15"  or daytemp.
What format should i usen for mqtt  :  ems-esp/thermostat {"cmd":nighttemp, "data": 15} it dose not working?

**Comment by proddy** [comment]
see https://emsesp.github.io/docs/#/MQTT?id=receiving-topics and note the text "`cmd is one of the commands listed in the Commands and must be enclosed in quotes`"

**Comment by pitulek** [comment]
ems-esp/thermostat    {"cmd":"nighttemp", "data":15, "id":"hc1"} 
not working, i do not know where is the mistake.

**Comment by MichaelDvP** [comment]
`{"cmd":"nighttemp", "data":15, "hc":1}` or `{"cmd":"nighttemp", "data":15, "id":1}` or `{"cmd":"nighttemp", "data":15}`

**Comment by pitulek** [comment]
thank you,{  "cmd":"nighttemp", "data":15, "id": "hc1" } working .  Thank you very much for your help!
