### ISSUE TITLE
What command for onetime water

### ISSUE THREAD

**Issue by pitulek** [proddy/EMS-ESP#563]
Hi!

What command is for onetimewater heat , is that  wwmode?

Is there any command for reset the boiler, because my sometimes hang on and i have to reset it with the button reset in the basement.

*Before creating a new issue please check that you have:*

* *searched the existing [issues](https://github.com/proddy/EMS-ESP/issues) (both open and closed)*
* *searched the [wiki help pages](https://bbqkees-electronics.nl/wiki/gateway/troubleshooting.html)*

*Completing this template will help developers and contributors help you. Try to be as specific and extensive as possible. If the information provided is not enough the issue will likely be closed.*

*You can now remove this line and the above ones. Text in italic is meant to be replaced by your own words. If any of the sections below are not relevant to the issue (for instance, the screenshots) then you can delete them.*

**Question**
*A clear and concise description of what the problem/doubt is.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Device information**
*Copy-paste here the information as it is outputted by the device. You can get this information by from the telnet session with the logging set to Verbose mode.*

**Additional context**
*Add any other context about the problem here.*

**Comment by proddy** [comment]
boiler reset is hard to implement and depends on the model. see https://github.com/proddy/EMS-ESP/issues/306

onetime command is `wwonetime`. I noticed the documentation at https://emsesp.github.io/docs/#/API?id=device-boiler is not up to date so need to work on that

**Comment by pitulek** [comment]
Thank you!

**Comment by proddy** [comment]
go into the Console, type `su` and the password (ems-esp-neo unless you changed it). Then type in `call` and you'll see all the possible commands per device. `wwonetime` should be in there.

<img width="804" alt="Screen Shot 2020-10-17 at 19 54 45" src="https://user-images.githubusercontent.com/1230712/96349862-9f6ee480-10b2-11eb-915d-dfe922108d22.png">

**Comment by pitulek** [comment]
Yes there is wwonetime. Thank you!
