### ISSUE TITLE
My Thermostat Moduline 1010H is recognized incorrectly

### ISSUE THREAD

**Issue by formadvi** [proddy/EMS-ESP#566]
The thermostat is recognized as RC300/RC310/Moduline 3000/CW400/Sense II.
The RC300/310 are more capable then 1010H if I am not mistaken.

Is this a bug or am I doing wrong assumption?

**Comment by proddy** [comment]
EMS devices are identified by a product ID. It looks like your Moduline 1010H shares the same ID as other thermostats. I'll add it to the device listing for clarity but it doesn't effect the working of EMS-ESP.
