### ISSUE TITLE
Difference in Free Memory Size and Fragmentation values between MQTT, Web and API

### ISSUE THREAD

**Issue by kwertie01** [proddy/EMS-ESP#569]
First a compliment to Proddy and al the other contributors of EMS-ESP. I'm now using this project for quite some time now and it is getting better every time :-)
 
I notice a difference in the values of Free Memory Size and Fragmentation in the Heartbeat MQTT message the Website and the API report. The values between the website and the API (report) are more equal but the values in the heartbeat MQTT message are more different.

I made this screenshot to show the difference
![image](https://user-images.githubusercontent.com/48419274/96639167-9899d900-1321-11eb-91e9-d462da5a9918.png)

here is the output of the API:
{
  "System": {
    "version": "2.1.0b9",
    "uptime": "000+05:02:03.428",
    **"freemem": 45,
    "fragmem": 6**
  }
Do I misinterpret these values or is this not ok?

**Comment by proddy** [comment]
yes this is normal. the free mem and frag and momentary measurements. The ones from the web are taken when the URL is loaded and before the resources are free'd up. I did experiment keeping these checks separate but they are also quite CPU intensive. Perhaps check every 30 seconds or so. Leave this issue open and I'll try out a few things.

**Comment by proddy** [comment]
I've removed this for 2.3 as it's misleading
