### ISSUE TITLE
Can we cause wearout of the eeproms built into the buderus electronics

### ISSUE THREAD

**Issue by hamster65** [proddy/EMS-ESP#570]
Just thinking: What happens if we use home automation and ems-esp to issue lot's of commands that change values that are stored e.g. in the rc35 eeprom. Like switching between night and day mode, or setting the target temperature every minute as part of a regulator... would that be an issue and damage the buderus electronics (eeproms) over time?

**Comment by bbqkees** [comment]
No most parameter changes will never end up in an EEPROM.
A boiler and thermostat are a control system with the inherent property of continuous state changes over its life time so it's designed to cope with that.

**Comment by hamster65** [comment]
So I could change settings like target temperature, summer/winter mode every second and it would not wear out the eeprom? How does rc35 retain those settings during a reset or power failure? I guess there is a battery or supercam inside of the rc35 unit for the clock, but I am not sure if that's used for settings, too.
