### ISSUE TITLE
Is there an easy way to reset to factory default?

### ISSUE THREAD

**Issue by bbqkees** [proddy/EMS-ESP#575]
Is there a (simple) way to do a factory reset without using pio erase?
(I could not find it but maybe its there.)

**Comment by proddy** [comment]
There's the console's format command. I think it's still there.

**Comment by proddy** [comment]
And also from the web ui.

**Comment by bbqkees** [comment]
Yes but I got someone who forgot the password.

**Comment by proddy** [comment]
Doh. No easy way I'm afraid. Take a copy of the settings using the web api system info and start again.

**Comment by MichaelDvP** [comment]
@bbqkees : The su-password is different from the admin-password in web. Does he forgot both passwords? 
Maybe a make version that clears the settings on espota-update, or is the espota-password also changed and forgotten or espota disabled?

**Comment by Victor-Mo** [comment]
Maybe have an option that 30 seconds after power-up you can do a factory reset from telnet without being logged in ? Or maybe a special password that can trigger it (in the first 30s). If you want it more secure, it only works when not connected to the EMS bus ?

**Comment by proddy** [comment]
version 1 had that feature. When it was booting and the LED was flashing for 5 seconds if you reset the ESP it would go into safe mode where you could reset to factory settings.

But as Michael pointed out if you forget the web admin password AND the console su password, then you better stick to gardening
