### ISSUE TITLE
Question: (REST API) Getting Invalid device response for mixer device type 

### ISSUE THREAD

**Issue by samvdb** [proddy/EMS-ESP#584]
When trying to get the info for a mixing module i get "Invalid device" as a response.

Example call: /api?device=mixer&cmd=info&id=hc1
I have tried many different combinations with id=hc 1, hc2 0x20 etc...

Where can i see a list of valid device names that can be used and how to i query these mixing valves?

![image](https://user-images.githubusercontent.com/632452/97432720-af8d8c00-191c-11eb-9032-39082da9dbc3.png)

**Comment by MichaelDvP** [comment]
There are some changes in the latest betas. One is renaming mixing to mixer. You are using a version with older `mixing`, so you have to use this in api too ` /api?device=mixing&cmd=info` and if you want to use the id, it's `id=1`.
Or update to latest version and use `mixer`.

**Comment by samvdb** [comment]
Thank you so much! Worked instantly!
