### ISSUE TITLE
Upgrade from 2.0.1 to 2.1.0 doesn't work with Upload firmware

### ISSUE THREAD

**Issue by rvanderven** [proddy/EMS-ESP#590]
I am running 2.0.1 on a WemosD1 mini and am trying to upgrade to 2.1.0.
I tried Upload Firmware and selected the EMS-ESP-2_1_0-esp8266.bin file, but nothing happens.
Also tries the espota.py script but that results in an error 
** File "espota.py", line 6
**  <!DOCTYPE html>
**    ^
** SyntaxError: invalid syntax

Any idea how to solve this?

**Comment by proddy** [comment]
did the upload via the web UI (2.0.1) not work? It can take around 2-3 minutes to upload, unpack and restart.

The espota.py script error - are you on Windows or Unix?

**Comment by rvanderven** [comment]
> did the upload via the web UI (2.0.1) not work? It can take around 2-3 minutes to upload, unpack and restart.
> 
> The espota.py script error - are you on Windows or Unix?
I did wait for more than 5 minutes (using Chrome)
I am a MacOS user.
Just tried again: what am I supposed to see when the upgrade succeeded?

**Comment by bbqkees** [comment]
If it succeeded you can refresh the page and it will show the new version number:
![image](https://user-images.githubusercontent.com/10775682/97814562-00d5ac80-1c8a-11eb-84fe-7bb0a06794ad.png)

**Comment by rvanderven** [comment]
The dashboard still shows 2.1.0

**Comment by rvanderven** [comment]
I did a reboot as well, prior trying the 2nd time

**Comment by rvanderven** [comment]
I managed to upgrade via espota.py. 
At 1st this didn't work, but I found out that I (stupily) saved the script via "save link as" which (of course) didn't download the python script itself, but the whole page which you see when you click on the link.
So I copied the python code and pasted it into the local espota.py file and managed to upload the code into my esp board.
This means the espota.py way works.
This of course still doesn't explain why the web based method didn't work.

**Comment by proddy** [comment]
I'll look into the Web upload again. We did have some issues prior to 2.0.1 with that feature.

Note the python scripts are also available in the /scripts folder of the EMS-ESP repo. https://emsesp.github.io/docs/#/Uploading-firmware?id=wirelessly-over-the-air-ota

**Comment by rvanderven** [comment]
Hi,

That is where I found the code, but I couldn't find a download button and I am not that familiar with GitHub.
I thought I could prevent copy/paste by using the save as but that was a wrong thought.
So I ended up in selecting the contents and paste this in my local file.

I am glad that you have found the issues in 2.0.1 wrt the web upload. Might be useful to mention this on the support page and direct users to using the OTA option.

Nice product by the way 👍


Grt

Richard

________________________________
Van: Proddy <notifications@github.com>
Verzonden: maandag 2 november 2020 08:22
Aan: proddy/EMS-ESP <EMS-ESP@noreply.github.com>
CC: rvanderven <richard.van.der.ven@live.nl>; State change <state_change@noreply.github.com>
Onderwerp: Re: [proddy/EMS-ESP] Upgrade from 2.0.1 to 2.1.0 doesn't work with Upload firmware (#590)


I'll look into the Web upload again. We did have some issues prior to 2.0.1 with that feature.

Note the python scripts are also available in the /scripts folder of the EMS-ESP repo. https://emsesp.github.io/docs/#/Uploading-firmware?id=wirelessly-over-the-air-ota<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Femsesp.github.io%2Fdocs%2F%23%2FUploading-firmware%3Fid%3Dwirelessly-over-the-air-ota&data=04%7C01%7C%7Ccd6537b83e2a47808c7b08d87f000b6d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637398985445522843%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PHchurHi0UVBlv%2FBTxgeofRp8%2B4wGLcBRUso27Mk6%2Bg%3D&reserved=0>
