### ISSUE TITLE
Service Code "unknow"

### ISSUE THREAD

**Issue by mupsje** [proddy/EMS-ESP#592]
After update firmware to v2.1.0b10

No service code in Hassio any more.
-did delete mqtt device.
-did restart ESP
-new devices showed up.
-no change.

![image](https://user-images.githubusercontent.com/46684538/97962783-29f35b80-1db6-11eb-9910-4a85525f43f8.png)

**Comment by proddy** [comment]
Looks like you're using an old 2.1 build. The MQTT topic has been renamed to `boiler_data`. Use MQTTExplorer to delete everything under ems-esp and homeassistant and reboot EMS-ESP. Then see if it works.

**Comment by proddy** [comment]
if its still a problem please re-open
