### ISSUE TITLE
Pull all mqtt-topics and vars

### ISSUE THREAD

**Issue by og9gjz567** [proddy/EMS-ESP#603]
Hi,
I've got a lot of shellies in my house. If I reboot my home assistant I publish a mqtt message with the topic shellies/announce, which will cause that every Shelly connected to the broker will respond with all available information.
more info: https://shelly-api-docs.shelly.cloud/#availability-and-announces

Is there something similiar? Do you think it would be a nice feature?

**Comment by proddy** [comment]
yes, that's a nice addition. There is a console command 'publish' which does the same so we can easily expose that as an API command, e.g. http://ems-esp/api?device=system&cmd=publish

**Comment by og9gjz567** [comment]
Very cool. I'll add this to my ha start!

**Comment by proddy** [comment]
you shouldn't need too since those MQTT topics have the retain flag. When HA reboots, it should just all work

**Comment by proddy** [comment]
in 2.1.1b2.
