### ISSUE TITLE
syslog: mqtt subscribe don't show up

### ISSUE THREAD

**Issue by susisstrolch** [proddy/EMS-ESP#623]
build: 963a08cfaa7ebf99d5184d433cf3e28a9bbf586f

Problem: sending a topic to EMS-ESP does not show up as MQTT log in syslog. Only MQTT publish are visible.

Loglevel is set to "ALL".

**Comment by proddy** [comment]
received MQTT topics are not shown in the log. You want to include them? Not a bug.

**Comment by susisstrolch** [comment]
Jep, would like to see them also in syslog.

**Comment by MichaelDvP** [comment]
@susisstrolch this is logged with EMSESP_DEBUG
pio_local.ini: 
```
[common]
debug_flags =
  -D EMSESP_DEBUG
```
