### ISSUE TITLE
Question: how to get 3.3v from ems bus? 

### ISSUE THREAD

**Issue by Chuckame** [proddy/EMS-ESP#626]
Hello there,

I've ordered the gateway last year. 

Do you know if it is possible to get 3.3v from ems bus? I've got a lm2596s voltage regulator, can I use it?

Thanks if you can help me 😁

**Comment by bbqkees** [comment]
Which board revision of the Gateway do you have?

**Comment by Chuckame** [comment]
V0.9, with an esp8266 or 12f

**Comment by bbqkees** [comment]
Ok then you don't have a Gateway, you have an EMS interface board.
The V0.9 interface board is not designed to draw power from the bus.
There is no pin to connect to and the resistor values of R9 to R12 are not compatible with powering an ESP via the bus.
However you can use the service jack to draw power from if your boiler has one.
You can use header J5 on the board for that purpose with the voltage regulator you suggest.

**Comment by Chuckame** [comment]
I haven't any jack on my boiler. But the j5 header is perfect! I will try
it

**Comment by bbqkees** [comment]
The service jack has a third pin with power that is wired to the board on J5.
If you do not have a service jack and are using the EMS bus wires via the screw terminal, you do not have this third pin available so it will not work.

**Comment by Chuckame** [comment]
Oh no, snif.
So no on-line power available for me :/
But the thermostat is working without battery, I hope I'll find how to get
power without a 220v adapter 😄

**Comment by bbqkees** [comment]
It's possible or course. The Gateway also works on just the bus but you have to modify the whole interface board to get it working in your case.

**Comment by Chuckame** [comment]
Too bad!

**Comment by Oderik** [comment]
@bbqkees do you plan on evolving your modules to support bus powering? I would really like that feature. It seems a bit odd that my super cool gateway + nodemcu need power outlet while the stupid thermostat is just powered by the two wires it's connected to... :)

**Comment by bbqkees** [comment]
@Oderik Yes that evolution has been available for a year now and it's called the Gateway Premium II.

You can't just draw an unsupervised amount of power from the bus for your own needs, you'll mess op the bus.
TX on the EMS bus works with a current signal, not a voltage signal. To work reliable, the EMS TX circuit must be tailored to a specific design each time.

The interface board is designed to provide a reliable bus interface for all use cases.
But being a bus-safe one-for-all solution, this does not include drawing power from that bus.

If you really want you can still modify an existing EMS interface board though and add some circuitry to power your NodeMCU from the bus.

**Comment by Chuckame** [comment]
Found this page that can be useful to get 15v, and after step down to 5v or 3v3: https://emsesp.github.io/docs/#/Building-your-own-test-circuit
