### ISSUE TITLE
MM100 Mixer - Pumpstatus is wrong

### ISSUE THREAD

**Issue by tp1de** [proddy/EMS-ESP#629]
I installed the last development version. But this error was existing in 2.1 stable version before.
The pumstatus for the MM100 mixer is wrong:

current pump status: on -> but pump is off 
                                  off -> but pump is on 

![grafik](https://user-images.githubusercontent.com/36480251/99959090-b62be980-2d8a-11eb-99aa-2d395efeb936.png)

**Comment by proddy** [comment]
Could you post the output of the 0x02D8 telegram? `read 21 2D8`

**Comment by tp1de** [comment]
Yes, if you tell me how to do it ....

**Comment by MichaelDvP** [comment]
Yes there is something wrong, pump and valve are read from the same address, pump should be pos 0 (according to Norbert).

**Comment by tp1de** [comment]
Is this what you mean for the telegram?

![image](https://user-images.githubusercontent.com/36480251/99962187-02c5f380-2d90-11eb-8c40-456ac8845b20.png)

**Comment by proddy** [comment]
yup, thats it. We're picking up the pump status from the 3rd byte 00 02 **00** 01 3A...
which looks incorrect.

**Comment by tp1de** [comment]
In general that is the pump status but just opposite way around: off means on and vice versa

**Comment by tp1de** [comment]
Just loaded new binary ....b5. Pump status is now ok
