### ISSUE TITLE
Auwch, what happened! Lost my boiler devices in home assistant....

### ISSUE THREAD

**Issue by bartplessers** [proddy/EMS-ESP#658]
Hello,

I was playing with my hass instance:

- rpi4
- docker with
  - homeassistant
  - mqtt broker
  - zigbee2mqtt
Don’t know what I messed up but I can’t see my (mqtt)boiler anymore. Device + entities seem “unavailable”.

However
- mqtt-broker up & running
- boiler is sending mqtt messages.
- other instances of hass on other devices, connected to same mqtt broker still see my boiler.

Is it possible to delete the device, but how to add it again? Boiler devices were added by autodiscovery…

No my dashboard looks sadly like…
![2020-12-11_16-41-32](https://user-images.githubusercontent.com/10470708/101924634-321e9200-3bd1-11eb-926d-5888db86e9da.png)

remark: the working temp display is from another mqtt sensor, proving that mqtt + hass works...

**Comment by proddy** [comment]
when EMS-ESP reboots it will re-create the HA discovery topics. They are also flagged as 'retained' messages so surprised they are gone. Look at the integrations in the HA system screen, under MQTT you'll see the EMS-ESP devices (or not)

**Comment by bartplessers** [comment]
yup, a reboot did the trick.
Devices were not available (before reboot), now they are.

cheers
B

**Comment by proddy** [comment]
@Neonox31 does this happen after you've upgraded EMS-ESP? It may be because the Device information changes due to the version. I've seen it happen once on my setup.

**Comment by Neonox31** [comment]
@proddy unfortunately I don't know because before I didn't have a home-assistant, I just installed it.
On the other hand I had several "cuts" but I haven't yet found out to which event they are related.
I will investigate.

**Comment by proddy** [comment]
in the meantime I'll make a change in the code so when any MQTT parameter is set and the Home Assistant format is being used it'll re-publish all the HA device details again.

**Comment by Neonox31** [comment]
> in the meantime I'll make a change in the code so when any MQTT parameter is set and the Home Assistant format is being used it'll re-publish all the HA device details again.

Good idea, I think it will solve the problem 👍

**Comment by proddy** [comment]
> > in the meantime I'll make a change in the code so when any MQTT parameter is set and the Home Assistant format is being used it'll re-publish all the HA device details again.
> 
> Good idea, I think it will solve the problem 👍

implemented in 2.3. Not sure if I'll back-port to 2.2 just yet
