### ISSUE TITLE
Show mqtt connection in info

### ISSUE THREAD

**Issue by kroon040** [proddy/EMS-ESP#66]
Hi,

Is is possible to show the mqtt info in the telnet session. Now I don't know the value of mqtt and als not if it is connected.

regards Richard

**Comment by proddy** [comment]
Is showing if it’s connected enough? Like it’s done with ‘ems bus
connected’.

**Comment by kroon040** [comment]
that should be also fine

**Comment by proddy** [comment]
in 1.5.5
