### ISSUE TITLE
holiday mode: How to specify away or at home?

### ISSUE THREAD

**Issue by hamster65** [proddy/EMS-ESP#671]
Hi,

I am trying to set holiday mode. The mqtt command looks like this:
{"cmd":"holiday","data":"24.12.2020-02.01.2021","id":"hc1"}
The result is that RC35 switches to holiday-absent mode (low heat until 2th January).
Since we are at home... how do I tell it that we are are _not_ away? There is no additional parameter in the documentation.

Using RC35, the first questions it asks is if we are at home or away during holiday.

Thanks!

btw if someone is interested: I use the node red date picker ui element and following function to create the mqtt string.
Start date is current date.

var d = new Date(msg.payload);
var day = d.getDate().toString().padStart(2, '0');
var month = (d.getMonth()+1).toString().padStart(2, '0');
var year = d.getFullYear();
datestring_to = day +"."+ month +"."+ year;

d = new Date();
day = d.getDate().toString().padStart(2, '0');
month = (d.getMonth()+1).toString().padStart(2, '0');
year = d.getFullYear();
datestring_from = day +"."+ month +"."+ year;

datestring = datestring_from + "-" + datestring_to;

msg.payload = "{\"cmd\":\"holiday\",\"data\":\"" + datestring + "\",\"id\":\"hc1\"}";

return msg;

**Comment by MichaelDvP** [comment]
For now it's only 'away from home'. I thought about how to implement and call a command (`vacation` for 'away'  and `holiday` for 'at home'?), but i think it's better not to spend ram to register a rarly used command. 
What do you think about the separator between the dates `-` for 'away'  and `+` for 'at home'? e.g. 
`call thermostat holiday 02.01.2021-09.01.2021` for away and `call thermostat holiday 06.02.2021+13.02.2021` for at home?

**Comment by hamster65** [comment]
Hi Michael, 
the + separator would work fine and I think its meaning would be clear.
The holiday function is really useful to us because of our work schedule. I am building a dedicated mqtt hardware button so set a holiday for the next day. And for actual holidays, It is very convenient to select the second day with on click through the ui.

**Comment by MichaelDvP** [comment]
Ok, you can try the dev. The RC35 supports one ' away from home' and one ' at home'  duration in addition for each heatingcircuit.  
If you want to check use `read 10 3F` for hc1, 49 for hc2.  'Away' is offset 87-92, 'at home' are the last 6 bytes (93-98) in order dmydmy.

**Comment by hamster65** [comment]
Thanks! It works fine, I tested with + and - . To end the holiday function (and before setting a new date), you have to dates in the past.
