### ISSUE TITLE
Support for longer host/server names @NTP server or @MQTT host settings

### ISSUE THREAD

**Issue by heinrich-peters** [proddy/EMS-ESP#676]
**Is your feature request related to a problem? Please describe.**
Specifying server names as FQDN seems good practice to me. The MQTT hostname and the NTP server name currently support only 32 characters.

**Describe the solution you'd like**
It would be great, if both input fields support longer inputs to allow specifying the server/host names as FQDN. It might be best to change the RegEx to verify the existence of "."-s in the hostname to ensure, that the hostname (without the domain part) does no exceed 32 characters. E.g. move from current test "^.{0,32}$" to "^[^.]{0,32}([.][^.]{1,32})*[.]?$". This will support
- the current 32 character hostname definition;
- FQDN with <32charaterHostname>.<32characterDomain>;
- FQDN with <32charaterHostname>.<32characterSub1Domain>.<32characterSub2Domain>.<32characterDomain>;
- ending hostname or FQDN with a "."

Thanks and BR, Heinrich

**Comment by proddy** [comment]
Nice addition. The 32 limit can be easily changed in
https://github.com/proddy/EMS-ESP/blob/908a7cda34a56ec874212c11acfd5909a1be5ad4/interface/src/validators/isHostname.ts#L1

and it shouldn't be too hard to add an extra validator for FQDN
