### ISSUE TITLE
New Boiler installation Buderus BG072

### ISSUE THREAD

**Issue by FirelightLokeren** [proddy/EMS-ESP#678]
Hi,

fot the moment I have on Bulex Themaclassic F30 controlled with Evohome on/off. The Boiler is 16 jears old and will be renewed on 15/01. The new boiler is a Buderus BG072. Last weak I already ordered the Evohome opentherm module and the netfit EMS-OT converter. Today i also ordered the Gateway Premium II, just for monitoring the boiler is Domoticz.

I hope i get everything connected and running.

Kind Regards 
Koen Deschepper

**Comment by proddy** [comment]
ok, good luck. It should be fine with the GB72

**Comment by FirelightLokeren** [comment]
Hi,

The Buderus GB072 is installed and working fine and all parameters are available in Domoticz.
Kind regards
