### ISSUE TITLE
MQTT topic path configurable

### ISSUE THREAD

**Issue by WeltenbummlerKA** [proddy/EMS-ESP#683]
**Is your feature request related to a problem? Please describe.**
The MQTT Topic is only the Hostname of the network setting or the Topic for Homeassistent.

**Describe the solution you'd like**
I would prefer to create an own Full Topic for the MQTT. So I can fully integrate to my existing topics. 
At the moment is called Junkers and I wanted it like show at the picture 1 below with Smarthome.

**Describe alternatives you've considered**
Maybe it's not difficult to integrate it like Tasmota (picture 2)?

**Additional context**
Picture 1:
<img width="217" alt="Bildschirmfoto 2021-01-08 um 07 51 56" src="https://user-images.githubusercontent.com/61679394/103983947-86903f80-5186-11eb-811e-e9805b9f90c0.png">

Picture 2:
<img width="379" alt="Bildschirmfoto 2021-01-08 um 07 54 50" src="https://user-images.githubusercontent.com/61679394/103984178-f0a8e480-5186-11eb-85c9-2c5a4deb7ede.png">

**Comment by proddy** [comment]
We had this in version 1.9 and removed it. It was called MQTT Base. Would it work if we bring it back and use it as a prefix to each topic, so instead of `ems-esp` it would be `<base>/<hostname>`?

**Comment by WeltenbummlerKA** [comment]
Maybe it will work like that with `<base>`. If it's possible to integrate it to modify the mqtt topic it would be helpful for my opinion. If not maybe there is a chance to change it direct at the code and make a binary by myself?

**Comment by MichaelDvP** [comment]
@proddy Is there a reason that the topic have to contain the hostname? Why not only a `<base>`  instead of `<hostname>` , that can be the same as the hostname, but also something completely different like a long path `home/heating/buderus`.

**Comment by proddy** [comment]
Depends on what problem you're trying to solve. Could you look at the current topic names in https://emsesp.github.io/docs/#/MQTT and let us know what you had in mind?

**Comment by proddy** [comment]
> @proddy Is there a reason that the topic have to contain the hostname? Why not only a `<base>` instead of `<hostname>` , that can be the same as the hostname, but also something completely different like a long path `home/heating/buderus`.

not really. I did this when I was running multiple versions of EMS-ESP for testing (e.g. ESP8266 and ESP32) and the hostname is the only unique identifier for a board.

I'm ok to bring back `<base>/%topic%` where the default <base> would be the Wifi hostname. I'll do a first implementation in the 2.3 branch.

**Comment by WeltenbummlerKA** [comment]
@proddy I use Tasmota and would like to have my mqtt topics equal. When I use only the hostname than I'm to restricted with the chars and also I get another topic in my FritzBox. It would be nice when you will implement that in the next branch.
Do you have also in mind maybe to implement it into ioBroker like you done with Home Assistent?

**Comment by MichaelDvP** [comment]
I've made a test build with base setting in the mqtt-settings. @WeltenbummlerKA Is this the way you think? [https://github.com/MichaelDvP/EMS-ESP/releases/tag/dev](https://github.com/MichaelDvP/EMS-ESP/releases/tag/dev)

Tasmota is another structure with %prefix% `tele`, `stat` and `cmnd`. I dont think it's the right for ems-esp. Do you have the tasmotas on mqtt-adapter in ioBroker or do you use the sonoff-adapter? 
To implement ems-esp to ioBroker it is not a function of ems-esp (like the HA-discovery), it needs a own adapter in ioBroker, or use the mqtt and a little script.

**Comment by proddy** [comment]
nice @MichaelDvP, that's how I would have implemented it too. I like the addition of the #sensor fails too. When accepted we'll need to merge these manually into the 2.3.

**Comment by MichaelDvP** [comment]
The `dallas_fails` are only published in `call system info` for now, but can be added t heartbeat too.  I use dallas with publish every minute and want to know if i miss some errors, but my 7 sensors do not have any error in 4 days i recorded. I think the spikes from another issue are caused by a faulty sensor.

**Comment by MichaelDvP** [comment]
@WeltenbummlerKA Have you tested the build? Please give a feedback. I'd like to get in sync with the official dev again, either by merging or deleting the `Base` changes.

**Comment by WeltenbummlerKA** [comment]
> I've made a test build with base setting in the mqtt-settings. @WeltenbummlerKA Is this the way you think? https://github.com/MichaelDvP/EMS-ESP/releases/tag/dev
> 
> Tasmota is another structure with %prefix% `tele`, `stat` and `cmnd`. I dont think it's the right for ems-esp. Do you have the tasmotas on mqtt-adapter in ioBroker or do you use the sonoff-adapter?
> To implement ems-esp to ioBroker it is not a function of ems-esp (like the HA-discovery), it needs a own adapter in ioBroker, or use the mqtt and a little script.

Sorry I didn't checked for new messages. I use mosquito as my mqtt broker. I will flash your code and tell you if it's better for me right now. I think that it will take time till next weekend because I'm temporary on a business trip.

**Comment by MichaelDvP** [comment]
Since there is no further feedback i've pushed the `Base` settings as mentioned. It's now in dev v2.2.1b1 and refactor-branch.
