### ISSUE TITLE
[Q] Is the Buderus GB142 with RC30 supported?

### ISSUE THREAD

**Issue by curlyel** [proddy/EMS-ESP#692]
Before considering EMS-ESP or especially before ordering the gateway from BBQKees, I'd like to find out, wether or not the Buderus GB142 heating system is supported yet or could be added easily?

The controller has an orange bus connector and a RC30 remote thermostat connected. A service jack on base controller is available too...

**Comment by proddy** [comment]
Pretty sure it does. Look at https://github.com/proddy/EMS-ESP/issues/387

**Comment by curlyel** [comment]
Excellent! Thanks for clarification!
