### ISSUE TITLE
Warm water circulation pump frequency - can not be changed (neither API nor MQTT)

### ISSUE THREAD

**Issue by tp1de** [proddy/EMS-ESP#703]
I tried to change the ww circulation pump frequency - but without success. 

On the thermostat I can change wwcircmode to  of,on,auto,own by web api or mqqt - both are working fine

On the boiler the changing of wwcircmode to values between 1..7 does not work. (API returns OK but no changes done)
Maybe the changes should be send to the thermostat? Any idea how to bring it to work?

ESP32:  v3.0.0b1 - RC310 / KB192i

**Comment by tp1de** [comment]
@MichaelDvP I did the code change but it is still not working ....

**Comment by MichaelDvP** [comment]
can you check with commands and `read 8 33` the values, for me it's working:
```
ems-esp:/# read 8 33
000+00:02:55.209 N 1: [emsesp] Boiler(0x08) -> Me(0x0B), UBAParameterWW(0x33), data: 08 FF 30 FB FF 28 FF 07 46 00 00
ems-esp:/# call boiler wwcircmode 5
000+00:03:11.391 I 2: [boiler] Setting warm water circulation mode 5x3min
ems-esp:/# read 8 33
000+00:03:20.269 N 3: [emsesp] Boiler(0x08) -> Me(0x0B), UBAParameterWW(0x33), data: 08 FF 30 FB FF 28 FF 05 46 00 00
ems-esp:/# call boiler wwcircmode 7
000+00:03:40.364 I 4: [boiler] Setting warm water circulation mode continuos
ems-esp:/# read 8 33
000+00:03:46.427 N 5: [emsesp] Boiler(0x08) -> Me(0x0B), UBAParameterWW(0x33), data: 08 FF 30 FB FF 28 FF 07 46 00 00
```

**Comment by tp1de** [comment]
No data:

![grafik](https://user-images.githubusercontent.com/36480251/108113079-4da58d80-7097-11eb-8ac0-c648e3c32773.png)

**Comment by tp1de** [comment]
I changed bus idto service key an tried again:  

![grafik](https://user-images.githubusercontent.com/36480251/108114373-00c2b680-7099-11eb-944e-719fb4fdbe18.png)

**Comment by MichaelDvP** [comment]
Ok, i think i've found it, please try again.

**Comment by tp1de** [comment]
@MichaelDvP 
It is working now - Super.

By the way one question: 
What is the difference between the datafields wWCirc and wWCircPump in boiler_data_ww?

**Comment by proddy** [comment]
@tp1de great! There's a brief description of the datafields in https://emsesp.github.io/docs/#/MQTT?id=thermostat

and thanks @MichaelDvP for the quick fix

**Comment by tp1de** [comment]
The definition:
wWCircPump = Warm water circulation pump available
wWCirc = Warm water circulation active

But in my case both values are the same and indicating when circulation pump is running. 
![grafik](https://user-images.githubusercontent.com/36480251/108185193-53898600-710c-11eb-92c7-d34692def873.png)

**Comment by MichaelDvP** [comment]
I think telegram 0xE9, boiler.cpp line 497 should be the status,`wWCirc` not the configuration. @tp1de Can you check that?
(wWCirc is also in E5, maybe no need to read it in E9).

**Comment by tp1de** [comment]
@MichaelDvP 

> I think telegram 0xE9, boiler.cpp line 497 should be the status,`wWCirc` not the configuration. @tp1de Can you check that?

Yes I can confirm - changing to wWCirc keeps wWCircPump constant on 1

> (wWCirc is also in E5, maybe no need to read it in E9).

Yes I can confirm too - for me no need to read wWCirc in E9 - for you @MichaelDvP  too?

**Comment by MichaelDvP** [comment]
E5 is the slow monitor sended periodically, maybe E9 status is triggered on change and more accurate. Can you check this with logging while wwCirc is triggered?

I have a ems-boiler and circulation is in telegrams 33 and 18. The boiler do not send 0xE telegrams and i can not test.

**Comment by tp1de** [comment]
I can't see any difference in MQTT Explorer:
1. first change to wWcirc
2. take message out in E9
![grafik](https://user-images.githubusercontent.com/36480251/108200910-678ab300-711f-11eb-887c-2f6b40ef2b80.png)

**Comment by MichaelDvP** [comment]
I've checked older logs: E9 is broadcasted completely every 10 sec, E5 is only sended out in parts whenever something changed. I think we should read both to have the current state (E9) and the change (E5). 
Fixed in dev8266 and dev32.
