### ISSUE TITLE
Upgrading to v3.0.0b3 - Lost of all config data

### ISSUE THREAD

**Issue by tp1de** [proddy/EMS-ESP#722]
While upgrading the esp32 from v3.0.0b1 to b3 all config data is lost (WLAN / MQTT / Settings)
This is not convinient .... any reason why?

**Comment by proddy** [comment]
yes, I switched to filesystems to LITTLEFS and changed the partition tables to support OTA better, so all the setting files have been removed. It's listed as a breaking change in the release notes. Sorry for the inconvenience.

**Comment by proddy** [comment]
hey, it's a development track. expect innovation!
