### ISSUE TITLE
Reduce TX-Modes to 0-4

### ISSUE THREAD

**Issue by MichaelDvP** [proddy/EMS-ESP#726]
The Tx-modes 5-255 are mainly a relict from esp32 development with it's different break logic (see #380, etc.). I think no one uses the modes with timer control. On v2 8266 memory is very low and the extra modes consumes some 100 bytes.  Also setting the right mode is not clear to all users. I suggest to use only modes 0-4 and replace the input by a dropdown list:
![tx_modes](https://user-images.githubusercontent.com/59284019/110158341-878dc800-7de9-11eb-9cbf-caea1c532999.png)

@proddy What do you think?

**Comment by proddy** [comment]
I think it's a wonderful idea! We would need to update the documentation to, especially to explain #4

**Comment by MichaelDvP** [comment]
v2, v3 and wiki updated.
