### ISSUE TITLE
Please do not change permanently mqtt datafield names

### ISSUE THREAD

**Issue by tp1de** [proddy/EMS-ESP#731]
@proddy @MichaelDvP 

I just installed v3.0.0b5 from bin and I recognized that datafield names by mgtt changed again.
I use a translation table from mqtt names toward my own datafields (km200 names) in a javascript program in ioBroker.
Whenever available I use ems-esp data, because it is more time-accurate then km200 data.

Please try to limit changes and if necessary please provide a table old-to-new names.

**Comment by proddy** [comment]
fair point. Some of the mixer names changed by another users PR. We'll include a breaking changes section in the changelog to make these more explicit.

**Comment by proddy** [comment]
added a section to the changelog
