### ISSUE TITLE
Suddenly new heating circuits hc3 and hc4 in mqtt and webui

### ISSUE THREAD

**Issue by tp1de** [proddy/EMS-ESP#736]
@MichaelDvP @proddy 

I recognized that I got 2 new heating circuits in my webui overview / mqtt data. (hc3 and hc4).
I just have 2  - hc1 (radiators) and hc2 (floorheating with mixer)

![grafik](https://user-images.githubusercontent.com/36480251/110458418-06298480-80cc-11eb-9e40-260f0c9795ee.png)

What happened ?

v3.0.0b5 with RC310/KB192i

**Comment by proddy** [comment]
this is a side effect of a change I made yesterday (https://github.com/proddy/EMS-ESP/commit/9d5bd11d268a61bbba8dcabacdb96db48b8829ac#commitcomment-47989818) which I should rollback.

**Comment by proddy** [comment]
did this problem go away with the latest dev firmware?
