### ISSUE TITLE
EMS power at 15V DC

### ISSUE THREAD

**Issue by mf01** [proddy/EMS-ESP#74]
Yesterday I've messured 15V DC at the EMS bus at GB172
Maybe this information is relevant to correct this part at README.

> powering from the EMS line, which is 15V A/C and using a buck converter as described above. Note the current design has stability issues when sending packages in this configuration so this is not recommended yet if you plan to many send commands to the thermostat or boiler.

**Comment by proddy** [comment]
thanks @mf01. It's a mistake. I'll change the doc - thanks for pointing this out.

**Comment by proddy** [comment]
in dev branch
