### ISSUE TITLE
(v3) firmware upload fails on Mac OSX (firefox, safari)

### ISSUE THREAD

**Issue by proddy** [proddy/EMS-ESP#741]
firmware update did not work on MAC (firefox, safari), work on Windows... (crome)

_Originally posted by @csubakk in https://github.com/proddy/EMS-ESP/issues/739#issuecomment-795202389_

**Comment by dia-de-muertos** [comment]
I can confirm this on Mac OS 11.2.2 with firefox86.
Can do tests as soon as a fix is available.

**Comment by proddy** [comment]
think i fixed it. tested with Chrome and Edge on OSX and Chrome on Win10

**Comment by csubakk** [comment]
I can help you, checking with safari and firefox on OSX.
