### ISSUE TITLE
Set time of EMS system using NTP

### ISSUE THREAD

**Issue by swa72** [proddy/EMS-ESP#743]
Does the EMS bus allow for setting the time of the system? If it is `call thermostat datetime`, can someone please give me an example of the format? Given that the ESP is hooked up to NTP, could it not set the time regularly?

**Comment by proddy** [comment]
See https://emsesp.github.io/docs/#/API?id=thermostat

@MichaelDvP implemented this, it works really well. If you choose 'ntp' it will take EMS-ESP's time.

**Comment by proddy** [comment]
Also see the original enhancement request https://github.com/proddy/EMS-ESP/issues/588. If it doesn't work let us know!
