### ISSUE TITLE
How do you (permanently) install the boards?

### ISSUE THREAD

**Issue by JF002** [proddy/EMS-ESP#85]
Hello,

I did some test with a wemos ESP8266 and the converter board from bbqkees. It works fine, and the values are published on my MQTT broker, great!

But the setup was not so great. The connection to the bus is made via a wire coming from behind of the thermostat, and both board are dangling below the thermostat.
I want to set the things up more permanently, and I was wondering what your setups look like ? Do you connect to the bus next to the boiler (mine does not have the service jack) or the thermostat? Are the boards secured in an enclosure? 
Do you have any recommandations to make it as safe as possible?

Thanks!

**Comment by proddy** [comment]
the latest bbqkees boards come with a pre-installed Wemos D1 and in a nicely packed enclosure with the USB exposed for power and two connectors for the EMS bus wires. You should check it out. The idea is that the unit is mounted onto the side of the boiler with double-sided tape.
