### ISSUE TITLE
Version 1.7 stable

### ISSUE THREAD

**Issue by gl3nni3** [proddy/EMS-ESP#93]
Hey Proddy,
Do you have any idea when version 1.7 is stable?

**Comment by gl3nni3** [comment]
@proddy

**Comment by proddy** [comment]
I haven't touched it for a while. If no one reports any issues I'll push it to master. Does 1.7 beta work with your changes?

**Comment by lobocobra** [comment]
I can confirm that it works at least solid for me :)

**Comment by higgers** [comment]
Seems to be working for me too (apart from the usual problem I have with my boiler not responding to requests but that's a known issue with my boiler.)

**Comment by SpaceTeddy** [comment]
for me it workes also fine!

**Comment by kwertie01** [comment]
The `set tx_delay` feature is working fine :-)

**Comment by proddy** [comment]
thanks for testing guys. One more change for the Solar Module then I'll push it to Master

**Comment by proddy** [comment]
@gl3nni3 is 1.7 working for you? I rewrote a lot of the original EMS+ code
